import type { Theme } from '../themeTypes';

export const BUILTIN_AMBER_ARCHIVE: Theme = {
  id: "builtin-amber-archive",
  name: "Amber Archive",
  mode: "light",
  tokens: {
    accent: "#9c5f2a",
    background: "#f7f3e8",
    surface: "#efe9db",
    surfaceElevated: "#e6dfce",
    surfaceMuted: "#faf7ef",
    border: "#d9d0c0",
    borderStrong: "#b8ae9c",
    textPrimary: "#2c2416",
    textSecondary: "#5a5040",
    textMuted: "#827868",
    foreground: "#2c2416",
    foregroundMuted: "#5a5040",
    foregroundSubtle: "#827868",
    accentHover: "#8a541f",
    accentForeground: "#ffffff",
    success: "#4a6b2a",
    successForeground: "#ffffff",
    warning: "#a06b1a",
    warningForeground: "#ffffff",
    danger: "#9b2c2c",
    dangerForeground: "#ffffff",
    info: "#3e6b8f",
    inputBackground: "#e6dfce",
    inputForeground: "#2c2416",
    placeholder: "#827868",
    disabledForeground: "#827868",
    buttonPrimaryBackground: "#9c5f2a",
    buttonPrimaryForeground: "#ffffff",
    buttonSecondaryBackground: "#e6dfce",
    buttonSecondaryForeground: "#2c2416",
    link: "#3e6b8f",
    focusRing: "#9c5f2a",
    selectionBackground: "#9c5f2a",
    selectionForeground: "#ffffff",
    overlay: "rgba(44, 36, 22, 0.25)",
    glow: "rgba(156, 95, 42, 0.18)",
  },
};
