import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_AMBER_ARCHIVE: ThemeFamily = {
  schemaVersion: 2,
  id: "amber-archive",
  name: "Amber Archive",
  aliases: ["builtin-amber-archive"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#9c5f2a",
      background: "#f7f3e8",
      surface: "#efe9db",
      surfaceElevated: "#e6dfce",
      surfaceMuted: "#faf7ef",
      border: "#d9d0c0",
      borderStrong: "#b8ae9c",
      textPrimary: "#2c2416",
      textSecondary: "#5a5040",
      textMuted: "#827868",
      foreground: "#2c2416",
      foregroundMuted: "#5a5040",
      foregroundSubtle: "#827868",
      accentHover: "#8a541f",
      accentForeground: "#ffffff",
      success: "#4a6b2a",
      successForeground: "#ffffff",
      warning: "#a06b1a",
      warningForeground: "#ffffff",
      danger: "#9b2c2c",
      dangerForeground: "#ffffff",
      info: "#3e6b8f",
      inputBackground: "#e6dfce",
      inputForeground: "#2c2416",
      placeholder: "#827868",
      disabledForeground: "#827868",
      buttonPrimaryBackground: "#9c5f2a",
      buttonPrimaryForeground: "#ffffff",
      buttonSecondaryBackground: "#e6dfce",
      buttonSecondaryForeground: "#2c2416",
      link: "#3e6b8f",
      focusRing: "#9c5f2a",
      selectionBackground: "#9c5f2a",
      selectionForeground: "#ffffff",
      overlay: "rgba(44, 36, 22, 0.25)",
      glow: "rgba(156, 95, 42, 0.18)",
      }),
      code: { preset: 'amber-archive', tokens: resolveCodeThemeTokens('amber-archive', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#16140d",
      surface: "#221f16",
      surfaceElevated: "#2e2a1e",
      border: "#494331",
      textPrimary: "#e5e3dc",
      textSecondary: "#b8b2a3",
      textMuted: "#958f7e",
      accent: "#d69a66",
      accentHover: "#dfaf86",
      accentForeground: "#0d1117",
      success: "#3fb950",
      warning: "#d29922",
      danger: "#f85149",
      info: "#58a6ff",
      focusRing: "#d69a66",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(214, 154, 102, 0.25)",
      surfaceMuted: "#1d1a11",
      borderStrong: "#84795d",
      }),
      code: { preset: 'amber-archive', tokens: resolveCodeThemeTokens('amber-archive', 'dark') },
    },
  },
};
