import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_ARCTIC_GLASS: ThemeFamily = {
  schemaVersion: 2,
  id: "arctic-glass",
  name: "Arctic Glass",
  aliases: ["builtin-arctic-glass"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#38bdf8",
      background: "#eef5f9",
      surface: "#e0eaef",
      surfaceElevated: "#d0dbe3",
      surfaceMuted: "#e8f0f5",
      border: "#c8d5dd",
      borderStrong: "#7f8d9b",
      textPrimary: "#1e293b",
      textSecondary: "#475569",
      textMuted: "#7a8fa8",
      foreground: "#1e293b",
      foregroundMuted: "#475569",
      foregroundSubtle: "#7a8fa8",
      accentHover: "#0ea5e9",
      accentForeground: "#1e293b",
      success: "#15803d",
      successForeground: "#ffffff",
      warning: "#f59e0b",
      warningForeground: "#1e293b",
      danger: "#b91c1c",
      dangerForeground: "#ffffff",
      info: "#3b82f6",
      inputBackground: "#d0dbe3",
      inputForeground: "#1e293b",
      placeholder: "#515f72",
      disabledForeground: "#7a8fa8",
      buttonPrimaryBackground: "#38bdf8",
      buttonPrimaryForeground: "#1e293b",
      buttonSecondaryBackground: "#d0dbe3",
      buttonSecondaryForeground: "#1e293b",
      link: "#0e65f4",
      focusRing: "#0369a1",
      selectionBackground: "#38bdf8",
      selectionForeground: "#1e293b",
      overlay: "rgba(30, 41, 59, 0.25)",
      glow: "rgba(56, 189, 248, 0.18)",
      }),
      code: { preset: 'arctic-glass', tokens: resolveCodeThemeTokens('arctic-glass', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#0d1316",
      surface: "#161e22",
      surfaceElevated: "#1e282e",
      border: "#314149",
      textPrimary: "#dce2e5",
      textSecondary: "#a3b0b8",
      textMuted: "#7e8d95",
      accent: "#44c1f8",
      accentHover: "#6bcefa",
      accentForeground: "#0d1117",
      success: "#3fb950",
      warning: "#d29922",
      danger: "#f85149",
      info: "#58a6ff",
      focusRing: "#44c1f8",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(68, 193, 248, 0.25)",
      surfaceMuted: "#11191d",
      borderStrong: "#5d7684",
      placeholder: "#829198",
      }),
      code: { preset: 'arctic-glass', tokens: resolveCodeThemeTokens('arctic-glass', 'dark') },
    },
  },
};
