import type { Theme } from '../themeTypes';

export const BUILTIN_ARCTIC_GLASS: Theme = {
  id: "builtin-arctic-glass",
  name: "Arctic Glass",
  mode: "light",
  tokens: {
    accent: "#38bdf8",
    background: "#eef5f9",
    surface: "#e0eaef",
    surfaceElevated: "#d0dbe3",
    surfaceMuted: "#e8f0f5",
    border: "#c8d5dd",
    borderStrong: "#a8b8c4",
    textPrimary: "#1e293b",
    textSecondary: "#475569",
    textMuted: "#7a8fa8",
    foreground: "#1e293b",
    foregroundMuted: "#475569",
    foregroundSubtle: "#7a8fa8",
    accentHover: "#0ea5e9",
    accentForeground: "#ffffff",
    success: "#22c55e",
    successForeground: "#ffffff",
    warning: "#f59e0b",
    warningForeground: "#1e293b",
    danger: "#ef4444",
    dangerForeground: "#ffffff",
    info: "#3b82f6",
    inputBackground: "#d0dbe3",
    inputForeground: "#1e293b",
    placeholder: "#7a8fa8",
    disabledForeground: "#7a8fa8",
    buttonPrimaryBackground: "#38bdf8",
    buttonPrimaryForeground: "#ffffff",
    buttonSecondaryBackground: "#d0dbe3",
    buttonSecondaryForeground: "#1e293b",
    link: "#3b82f6",
    focusRing: "#38bdf8",
    selectionBackground: "#38bdf8",
    selectionForeground: "#ffffff",
    overlay: "rgba(30, 41, 59, 0.25)",
    glow: "rgba(56, 189, 248, 0.18)",
  },
};
