import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_AURORA_BOREAL: ThemeFamily = {
  schemaVersion: 2,
  id: "aurora-boreal",
  name: "Aurora Boreal",
  aliases: ["builtin-aurora-boreal"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f5f7f7",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#cbd4d7",
      textPrimary: "#1a2529",
      textSecondary: "#496169",
      textMuted: "#647e87",
      accent: "#077e4c",
      accentHover: "#05613a",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#077e4c",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(7, 126, 76, 0.18)",
      surfaceMuted: "#eceff0",
      borderStrong: "#7e9097",
      placeholder: "#607982",
      }),
      code: { preset: 'aurora-boreal', tokens: resolveCodeThemeTokens('aurora-boreal', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#4dffb4",
      background: "#021015",
      surface: "#0a1f1a",
      surfaceElevated: "#122e28",
      surfaceMuted: "#051812",
      border: "#1a3530",
      borderStrong: "#436760",
      textPrimary: "#e0f7fa",
      textSecondary: "#a3d5d0",
      textMuted: "#5a8a82",
      foreground: "#e0f7fa",
      foregroundMuted: "#a3d5d0",
      foregroundSubtle: "#5a8a82",
      accentHover: "#7fffd4",
      accentForeground: "#021015",
      success: "#2ecc71",
      successForeground: "#021015",
      warning: "#f39c12",
      warningForeground: "#021015",
      danger: "#e74c3c",
      dangerForeground: "#021015",
      info: "#3498db",
      inputBackground: "#122e28",
      inputForeground: "#e0f7fa",
      placeholder: "#659b92",
      disabledForeground: "#5a8a82",
      buttonPrimaryBackground: "#4dffb4",
      buttonPrimaryForeground: "#021015",
      buttonSecondaryBackground: "#122e28",
      buttonSecondaryForeground: "#e0f7fa",
      link: "#3498db",
      focusRing: "#4dffb4",
      selectionBackground: "#4dffb4",
      selectionForeground: "#021015",
      overlay: "rgba(2, 16, 21, 0.7)",
      glow: "rgba(77, 255, 180, 0.25)",
      }),
      code: { preset: 'aurora-boreal', tokens: resolveCodeThemeTokens('aurora-boreal', 'dark') },
    },
  },
};
