import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_BASALT_NOIR: ThemeFamily = {
  schemaVersion: 2,
  id: "basalt-noir",
  name: "Basalt Noir",
  aliases: ["builtin-basalt-noir"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f6f6f6",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#d3d0cf",
      textPrimary: "#23201f",
      textSecondary: "#5e5755",
      textMuted: "#7a7371",
      accent: "#cb3e0b",
      accentHover: "#ae3509",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#cb3e0b",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(203, 62, 11, 0.18)",
      surfaceMuted: "#efeeee",
      borderStrong: "#918c8b",
      }),
      code: { preset: 'basalt-noir', tokens: resolveCodeThemeTokens('basalt-noir', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#ff6b35",
      background: "#141414",
      surface: "#1e1e1e",
      surfaceElevated: "#282828",
      surfaceMuted: "#181818",
      border: "#383838",
      borderStrong: "#636362",
      textPrimary: "#f0ebe5",
      textSecondary: "#c8c0b8",
      textMuted: "#888078",
      foreground: "#f0ebe5",
      foregroundMuted: "#c8c0b8",
      foregroundSubtle: "#888078",
      accentHover: "#ff8c5a",
      accentForeground: "#141414",
      success: "#7cb342",
      successForeground: "#141414",
      warning: "#ffa726",
      warningForeground: "#141414",
      danger: "#ef5350",
      dangerForeground: "#141414",
      info: "#42a5f5",
      inputBackground: "#282828",
      inputForeground: "#f0ebe5",
      placeholder: "#968f87",
      disabledForeground: "#888078",
      buttonPrimaryBackground: "#ff6b35",
      buttonPrimaryForeground: "#141414",
      buttonSecondaryBackground: "#282828",
      buttonSecondaryForeground: "#f0ebe5",
      link: "#42a5f5",
      focusRing: "#ff6b35",
      selectionBackground: "#ff6b35",
      selectionForeground: "#141414",
      overlay: "rgba(20, 20, 20, 0.7)",
      glow: "rgba(255, 107, 53, 0.25)",
      }),
      code: { preset: 'basalt-noir', tokens: resolveCodeThemeTokens('basalt-noir', 'dark') },
    },
  },
};
