import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_CATPPUCCIN: ThemeFamily = {
  schemaVersion: 2,
  id: "catppuccin",
  name: "Forge Catppuccin",
  aliases: ["builtin-catppuccin"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f6f6f7",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#ceced4",
      textPrimary: "#1e1e24",
      textSecondary: "#525260",
      textMuted: "#6e6e7d",
      accent: "#d5164b",
      accentHover: "#b91341",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#d5164b",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(213, 22, 75, 0.18)",
      surfaceMuted: "#eeeeef",
      borderStrong: "#8e8e99",
      }),
      code: { preset: 'catppuccin', tokens: resolveCodeThemeTokens('catppuccin', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#1e1e2e",
      surface: "#313244",
      surfaceElevated: "#45475a",
      border: "#6c7086",
      textPrimary: "#cdd6f4",
      textSecondary: "#a6adc8",
      textMuted: "#8c91aa",
      placeholder: "#8f95ae",
      accent: "#f38ba8",
      accentHover: "#fab387",
      accentForeground: "#1e1e2e",
      success: "#a6e3a1",
      warning: "#f9e2af",
      danger: "#f38ba8",
      info: "#89dceb",
      focusRing: "#f38ba8",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(243, 139, 168, 0.25)",
      surfaceMuted: "#181825",
      borderStrong: "#cdd6f4",
      }),
      code: { preset: 'catppuccin', tokens: resolveCodeThemeTokens('catppuccin', 'dark') },
    },
  },
};
