import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_CIRCUIT_MINT: ThemeFamily = {
  schemaVersion: 2,
  id: "circuit-mint",
  name: "Circuit Mint",
  aliases: ["builtin-circuit-mint"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f6f6f7",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#cfd2d3",
      textPrimary: "#1f2324",
      textSecondary: "#545c5e",
      textMuted: "#70797b",
      accent: "#168358",
      accentHover: "#116946",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#168358",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(22, 131, 88, 0.18)",
      surfaceMuted: "#eeefef",
      borderStrong: "#909698",
      }),
      code: { preset: 'circuit-mint', tokens: resolveCodeThemeTokens('circuit-mint', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#6ee7b7",
      background: "#0d1112",
      surface: "#161d1f",
      surfaceElevated: "#1f292c",
      surfaceMuted: "#111719",
      border: "#2d3a3e",
      borderStrong: "#4a5c61",
      textPrimary: "#e8f5f0",
      textSecondary: "#aec4bf",
      textMuted: "#718984",
      foreground: "#e8f5f0",
      foregroundMuted: "#aec4bf",
      foregroundSubtle: "#718984",
      accentHover: "#8befc9",
      accentForeground: "#0d1112",
      success: "#5fd68a",
      successForeground: "#0d1112",
      warning: "#f0c24d",
      warningForeground: "#0d1112",
      danger: "#f06b6b",
      dangerForeground: "#0d1112",
      info: "#7dd3fc",
      inputBackground: "#1f292c",
      inputForeground: "#e8f5f0",
      placeholder: "#718984",
      disabledForeground: "#718984",
      buttonPrimaryBackground: "#6ee7b7",
      buttonPrimaryForeground: "#0d1112",
      buttonSecondaryBackground: "#1f292c",
      buttonSecondaryForeground: "#e8f5f0",
      link: "#7dd3fc",
      focusRing: "#6ee7b7",
      selectionBackground: "#6ee7b7",
      selectionForeground: "#0d1112",
      overlay: "rgba(13, 17, 18, 0.7)",
      glow: "rgba(110, 231, 183, 0.25)",
      }),
      code: { preset: 'circuit-mint', tokens: resolveCodeThemeTokens('circuit-mint', 'dark') },
    },
  },
};
