import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_COPPER: ThemeFamily = {
  schemaVersion: 2,
  id: "copper",
  name: "Forge Copper",
  aliases: ["builtin-copper"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f5f6f7",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#ced0d5",
      textPrimary: "#1d2025",
      textSecondary: "#505762",
      textMuted: "#6c737f",
      accent: "#ab5f21",
      accentHover: "#91511c",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#ab5f21",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(171, 95, 33, 0.18)",
      surfaceMuted: "#edeef0",
      borderStrong: "#898d96",
      }),
      code: { preset: 'copper', tokens: resolveCodeThemeTokens('copper', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#0d1117",
      surface: "#161b22",
      surfaceElevated: "#1c2330",
      border: "#2a3140",
      textPrimary: "#d0d7de",
      textSecondary: "#9aa7b8",
      textMuted: "#808b9b",
      accent: "#a65c20",
      accentHover: "#bf6d2d",
      accentForeground: "#ffffff",
      success: "#3fb950",
      warning: "#d29922",
      danger: "#f85149",
      info: "#58a6ff",
      focusRing: "#d98e4d",
      overlay: "rgba(0,0,0,0.6)",
      glow: "rgba(199,123,59,0.25)",
      surfaceMuted: "#11161d",
      borderStrong: "#6b7686",
      }),
      code: { preset: 'copper', tokens: resolveCodeThemeTokens('copper', 'dark') },
    },
  },
};
