import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_COTTON_CANDY_CONSOLE: ThemeFamily = {
  schemaVersion: 2,
  id: "cotton-candy-console",
  name: "Cotton Candy Console",
  aliases: ["builtin-cotton-candy-console","cotton-candy-console"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#7FB8C7",
      background: "#EAF3F5",
      surface: "#F3EDEB",
      surfaceElevated: "#FFFFFF",
      surfaceMuted: "#EBD0D7",
      border: "#B7C9D3",
      borderStrong: "#869CB1",
      textPrimary: "#412A3A",
      textSecondary: "#574457",
      textMuted: "#614E61",
      foreground: "#412A3A",
      foregroundMuted: "#574457",
      foregroundSubtle: "#614E61",
      accentHover: "#69A7B7",
      accentForeground: "#1F141C",
      success: "#2D7A5C",
      successForeground: "#FFFFFF",
      warning: "#A35C2B",
      warningForeground: "#FFFFFF",
      danger: "#AA5B6E",
      dangerForeground: "#FFFFFF",
      info: "#415C73",
      inputBackground: "#FFFFFF",
      inputForeground: "#412A3A",
      placeholder: "#614E61",
      disabledForeground: "#614E61",
      buttonPrimaryBackground: "#7FB8C7",
      buttonPrimaryForeground: "#1F141C",
      buttonSecondaryBackground: "#EBD0D7",
      buttonSecondaryForeground: "#412A3A",
      link: "#3B6B80",
      focusRing: "#AA5B6E",
      selectionBackground: "#D6E9ED",
      selectionForeground: "#412A3A",
      overlay: "rgba(65, 42, 58, 0.4)",
      glow: "rgba(127, 184, 199, 0.25)",
      }),
      code: { preset: 'cotton-candy-console', tokens: resolveCodeThemeTokens('cotton-candy-console', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#0d1516",
      surface: "#162022",
      surfaceElevated: "#1e2b2e",
      border: "#314549",
      textPrimary: "#dce3e5",
      textSecondary: "#a3b4b8",
      textMuted: "#7e9195",
      accent: "#72b8ca",
      accentHover: "#90c7d5",
      accentForeground: "#0d1117",
      success: "#3fb950",
      warning: "#d29922",
      danger: "#f85149",
      info: "#58a6ff",
      focusRing: "#72b8ca",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(114, 184, 202, 0.25)",
      surfaceMuted: "#111b1d",
      borderStrong: "#5d7d84",
      }),
      code: { preset: 'cotton-candy-console', tokens: resolveCodeThemeTokens('cotton-candy-console', 'dark') },
    },
  },
};
