import type { Theme } from '../themeTypes';

export const BUILTIN_COTTON_CANDY_CONSOLE: Theme = {
  id: "cotton-candy-console",
  name: "Cotton Candy Console",
  mode: "light",
  tokens: {
    accent: "#7FB8C7",
    background: "#EAF3F5",
    surface: "#F3EDEB",
    surfaceElevated: "#FFFFFF",
    surfaceMuted: "#EBD0D7",
    border: "#B7C9D3",
    borderStrong: "#869CB1",
    textPrimary: "#412A3A",
    textSecondary: "#574457",
    textMuted: "#614E61",
    foreground: "#412A3A",
    foregroundMuted: "#574457",
    foregroundSubtle: "#614E61",
    accentHover: "#69A7B7",
    accentForeground: "#1F141C",
    success: "#2D7A5C",
    successForeground: "#FFFFFF",
    warning: "#A35C2B",
    warningForeground: "#FFFFFF",
    danger: "#AA5B6E",
    dangerForeground: "#FFFFFF",
    info: "#415C73",
    inputBackground: "#FFFFFF",
    inputForeground: "#412A3A",
    placeholder: "#614E61",
    disabledForeground: "#614E61",
    buttonPrimaryBackground: "#7FB8C7",
    buttonPrimaryForeground: "#1F141C",
    buttonSecondaryBackground: "#EBD0D7",
    buttonSecondaryForeground: "#412A3A",
    link: "#3B6B80",
    focusRing: "#AA5B6E",
    selectionBackground: "#D6E9ED",
    selectionForeground: "#412A3A",
    overlay: "rgba(65, 42, 58, 0.4)",
    glow: "rgba(127, 184, 199, 0.25)",
  },
};
