import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_CYBER_ORCHID: ThemeFamily = {
  schemaVersion: 2,
  id: "cyber-orchid",
  name: "Cyber Orchid",
  aliases: ["builtin-cyber-orchid"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f6f5f7",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#d2cbd7",
      textPrimary: "#221a29",
      textSecondary: "#5c4969",
      textMuted: "#786487",
      accent: "#750cdf",
      accentHover: "#660ac2",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#750cdf",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(117, 12, 223, 0.18)",
      surfaceMuted: "#efecf0",
      borderStrong: "#9687a1",
      }),
      code: { preset: 'cyber-orchid', tokens: resolveCodeThemeTokens('cyber-orchid', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#c084fc",
      background: "#0d0612",
      surface: "#1a1125",
      surfaceElevated: "#271c35",
      surfaceMuted: "#140e1c",
      border: "#3a2d48",
      borderStrong: "#5a4d68",
      textPrimary: "#f3e8ff",
      textSecondary: "#d4c4e8",
      textMuted: "#9a8ab0",
      foreground: "#f3e8ff",
      foregroundMuted: "#d4c4e8",
      foregroundSubtle: "#9a8ab0",
      accentHover: "#d8a8ff",
      accentForeground: "#0d0612",
      success: "#86efac",
      successForeground: "#0d0612",
      warning: "#fde047",
      warningForeground: "#0d0612",
      danger: "#f87171",
      dangerForeground: "#0d0612",
      info: "#93c5fd",
      inputBackground: "#271c35",
      inputForeground: "#f3e8ff",
      placeholder: "#9a8ab0",
      disabledForeground: "#9a8ab0",
      buttonPrimaryBackground: "#c084fc",
      buttonPrimaryForeground: "#0d0612",
      buttonSecondaryBackground: "#271c35",
      buttonSecondaryForeground: "#f3e8ff",
      link: "#93c5fd",
      focusRing: "#c084fc",
      selectionBackground: "#c084fc",
      selectionForeground: "#0d0612",
      overlay: "rgba(13, 6, 18, 0.7)",
      glow: "rgba(192, 132, 252, 0.25)",
      }),
      code: { preset: 'cyber-orchid', tokens: resolveCodeThemeTokens('cyber-orchid', 'dark') },
    },
  },
};
