import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_DARK: ThemeFamily = {
  schemaVersion: 2,
  id: "dark",
  name: "Forge Graphite",
  aliases: ["builtin-dark"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f4f6f8",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#d0d7de",
      textPrimary: "#1f2328",
      textSecondary: "#57606a",
      textMuted: "#656d76",
      accent: "#1a6fd6",
      accentHover: "#3581e6",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#1a6fd6",
      overlay: "rgba(0,0,0,0.4)",
      glow: "rgba(26,111,214,0.18)",
      surfaceMuted: "#eaeef2",
      borderStrong: "#8c959f",
      }),
      code: { preset: 'dark', tokens: resolveCodeThemeTokens('dark', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#0d1117",
      surface: "#161b22",
      surfaceElevated: "#1c2330",
      border: "#2a3140",
      textPrimary: "#d0d7de",
      textSecondary: "#9aa7b8",
      textMuted: "#808b9b",
      accent: "#1a6fd6",
      accentHover: "#3581e6",
      accentForeground: "#ffffff",
      success: "#3fb950",
      warning: "#d29922",
      danger: "#f85149",
      info: "#58a6ff",
      focusRing: "#4c93f8",
      overlay: "rgba(0,0,0,0.6)",
      glow: "rgba(47,129,247,0.25)",
      surfaceMuted: "#11161d",
      borderStrong: "#6b7686",
      }),
      code: { preset: 'dark', tokens: resolveCodeThemeTokens('dark', 'dark') },
    },
  },
};
