import type { Theme } from '../themeTypes';

export const BUILTIN_DESERT_COPPERFIELD: Theme = {
  id: "builtin-desert-copperfield",
  name: "Desert Copperfield",
  mode: "light",
  tokens: {
    accent: "#9c5f2a",
    background: "#fdf8f5",
    surface: "#f5ebe4",
    surfaceElevated: "#ece0d6",
    surfaceMuted: "#faf4ef",
    border: "#dccfc4",
    borderStrong: "#bcafa4",
    textPrimary: "#3d2914",
    textSecondary: "#6b5640",
    textMuted: "#9a8a78",
    foreground: "#3d2914",
    foregroundMuted: "#6b5640",
    foregroundSubtle: "#9a8a78",
    accentHover: "#8a541f",
    accentForeground: "#ffffff",
    success: "#556b1e",
    successForeground: "#ffffff",
    warning: "#a85412",
    warningForeground: "#ffffff",
    danger: "#b22222",
    dangerForeground: "#ffffff",
    info: "#4682b4",
    inputBackground: "#ece0d6",
    inputForeground: "#3d2914",
    placeholder: "#9a8a78",
    disabledForeground: "#9a8a78",
    buttonPrimaryBackground: "#9c5f2a",
    buttonPrimaryForeground: "#ffffff",
    buttonSecondaryBackground: "#ece0d6",
    buttonSecondaryForeground: "#3d2914",
    link: "#4682b4",
    focusRing: "#9c5f2a",
    selectionBackground: "#9c5f2a",
    selectionForeground: "#ffffff",
    overlay: "rgba(61, 41, 20, 0.25)",
    glow: "rgba(156, 95, 42, 0.18)",
  },
};
