import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_DESERT_COPPERFIELD: ThemeFamily = {
  schemaVersion: 2,
  id: "desert-copperfield",
  name: "Desert Copperfield",
  aliases: ["builtin-desert-copperfield"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#9c5f2a",
      background: "#fdf8f5",
      surface: "#f5ebe4",
      surfaceElevated: "#ece0d6",
      surfaceMuted: "#faf4ef",
      border: "#dccfc4",
      borderStrong: "#9b8d7f",
      textPrimary: "#3d2914",
      textSecondary: "#6b5640",
      textMuted: "#9a8a78",
      foreground: "#3d2914",
      foregroundMuted: "#6b5640",
      foregroundSubtle: "#9a8a78",
      accentHover: "#8a541f",
      accentForeground: "#ffffff",
      success: "#556b1e",
      successForeground: "#ffffff",
      warning: "#a85412",
      warningForeground: "#ffffff",
      danger: "#b22222",
      dangerForeground: "#ffffff",
      info: "#4682b4",
      inputBackground: "#ece0d6",
      inputForeground: "#3d2914",
      placeholder: "#8d7d6b",
      disabledForeground: "#9a8a78",
      buttonPrimaryBackground: "#9c5f2a",
      buttonPrimaryForeground: "#ffffff",
      buttonSecondaryBackground: "#ece0d6",
      buttonSecondaryForeground: "#3d2914",
      link: "#4076a4",
      focusRing: "#9c5f2a",
      selectionBackground: "#9c5f2a",
      selectionForeground: "#ffffff",
      overlay: "rgba(61, 41, 20, 0.25)",
      glow: "rgba(156, 95, 42, 0.18)",
      }),
      code: { preset: 'desert-copperfield', tokens: resolveCodeThemeTokens('desert-copperfield', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#16110d",
      surface: "#221a16",
      surfaceElevated: "#2e241e",
      border: "#493a31",
      textPrimary: "#e5dfdc",
      textSecondary: "#b8aba3",
      textMuted: "#95877e",
      accent: "#d69a66",
      accentHover: "#dfaf86",
      accentForeground: "#0d1117",
      success: "#3fb950",
      warning: "#d29922",
      danger: "#f85149",
      info: "#58a6ff",
      focusRing: "#d69a66",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(214, 154, 102, 0.25)",
      surfaceMuted: "#1d1611",
      borderStrong: "#846b5d",
      }),
      code: { preset: 'desert-copperfield', tokens: resolveCodeThemeTokens('desert-copperfield', 'dark') },
    },
  },
};
