import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_DRACULA: ThemeFamily = {
  schemaVersion: 2,
  id: "dracula",
  name: "Forge Dracula",
  aliases: ["builtin-dracula"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f6f6f6",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#cfd0d3",
      textPrimary: "#1f2023",
      textSecondary: "#54565e",
      textMuted: "#70727b",
      accent: "#630cde",
      accentHover: "#560bc1",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#630cde",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(99, 12, 222, 0.18)",
      surfaceMuted: "#eeeeef",
      borderStrong: "#8c8d93",
      }),
      code: { preset: 'dracula', tokens: resolveCodeThemeTokens('dracula', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#282a36",
      surface: "#343748",
      surfaceElevated: "#44475a",
      border: "#52566e",
      textPrimary: "#f8f8f2",
      textSecondary: "#bfbfbf",
      textMuted: "#9e9fb4",
      accent: "#bd93f9",
      accentHover: "#ff79c6",
      accentForeground: "#282a36",
      success: "#50fa7b",
      warning: "#f1fa8c",
      danger: "#ff5555",
      info: "#8be9fd",
      focusRing: "#bd93f9",
      overlay: "rgba(40,42,54,0.7)",
      glow: "rgba(189,147,249,0.2)",
      surfaceMuted: "#303241",
      borderStrong: "#737896",
      foregroundSubtle: "#a8a9bd",
      placeholder: "#b6b7c7",
      disabledForeground: "#9293aa",
      link: "#8be9fd",
      }),
      code: { preset: 'dracula', tokens: resolveCodeThemeTokens('dracula', 'dark') },
    },
  },
};
