import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_DUAL_PERSONA: ThemeFamily = {
  schemaVersion: 2,
  id: "dual-persona",
  name: "Dual Persona",
  aliases: ["builtin-dual-persona"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#86BDCB",
      background: "#E9EEF2",
      surface: "#F3EDEB",
      surfaceElevated: "#FFFFFF",
      surfaceMuted: "#F2DFE7",
      border: "#C3B4C9",
      borderStrong: "#808798",
      textPrimary: "#412A3A",
      textSecondary: "#574457",
      textMuted: "#614E61",
      foreground: "#412A3A",
      foregroundMuted: "#574457",
      foregroundSubtle: "#614E61",
      accentHover: "#6FAFC0",
      accentForeground: "#1F141C",
      success: "#2B785B",
      successForeground: "#FFFFFF",
      warning: "#A85E2E",
      warningForeground: "#FFFFFF",
      danger: "#B84E70",
      dangerForeground: "#FFFFFF",
      info: "#74528A",
      inputBackground: "#F2DFE7",
      inputForeground: "#412A3A",
      placeholder: "#614E61",
      disabledForeground: "#614E61",
      buttonPrimaryBackground: "#86BDCB",
      buttonPrimaryForeground: "#1F141C",
      buttonSecondaryBackground: "#F2DFE7",
      buttonSecondaryForeground: "#412A3A",
      link: "#3C6D7E",
      focusRing: "#AA5B6E",
      selectionBackground: "#D8E8EC",
      selectionForeground: "#412A3A",
      overlay: "rgba(65, 42, 58, 0.4)",
      glow: "rgba(134, 189, 203, 0.25)",
      }),
      code: { preset: 'dual-persona', tokens: resolveCodeThemeTokens('dual-persona', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#0e1216",
      surface: "#171d21",
      surfaceElevated: "#20272d",
      border: "#333e47",
      textPrimary: "#dde1e4",
      textSecondary: "#a5aeb6",
      textMuted: "#808b93",
      accent: "#72b8ca",
      accentHover: "#90c7d5",
      accentForeground: "#0d1117",
      success: "#3fb950",
      warning: "#d29922",
      danger: "#f85149",
      info: "#58a6ff",
      focusRing: "#72b8ca",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(114, 184, 202, 0.25)",
      surfaceMuted: "#12171c",
      borderStrong: "#607280",
      placeholder: "#859097",
      }),
      code: { preset: 'dual-persona', tokens: resolveCodeThemeTokens('dual-persona', 'dark') },
    },
  },
};
