import type { Theme } from '../themeTypes';

export const BUILTIN_DUAL_PERSONA: Theme = {
  id: "dual-persona",
  name: "Dual Persona",
  mode: "light",
  tokens: {
    accent: "#86BDCB",
    background: "#E9EEF2",
    surface: "#F3EDEB",
    surfaceElevated: "#FFFFFF",
    surfaceMuted: "#F2DFE7",
    border: "#C3B4C9",
    borderStrong: "#9AAFC0",
    textPrimary: "#412A3A",
    textSecondary: "#574457",
    textMuted: "#614E61",
    foreground: "#412A3A",
    foregroundMuted: "#574457",
    foregroundSubtle: "#614E61",
    accentHover: "#6FAFC0",
    accentForeground: "#1F141C",
    success: "#2B785B",
    successForeground: "#FFFFFF",
    warning: "#A85E2E",
    warningForeground: "#FFFFFF",
    danger: "#B84E70",
    dangerForeground: "#FFFFFF",
    info: "#74528A",
    inputBackground: "#F2DFE7",
    inputForeground: "#412A3A",
    placeholder: "#614E61",
    disabledForeground: "#614E61",
    buttonPrimaryBackground: "#86BDCB",
    buttonPrimaryForeground: "#1F141C",
    buttonSecondaryBackground: "#F2DFE7",
    buttonSecondaryForeground: "#412A3A",
    link: "#3C6D7E",
    focusRing: "#AA5B6E",
    selectionBackground: "#D8E8EC",
    selectionForeground: "#412A3A",
    overlay: "rgba(65, 42, 58, 0.4)",
    glow: "rgba(134, 189, 203, 0.25)",
  },
};
