import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_EMBER_MONASTERY: ThemeFamily = {
  schemaVersion: 2,
  id: "ember-monastery",
  name: "Ember Monastery",
  aliases: ["builtin-ember-monastery"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f7f6f5",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#d5d0cd",
      textPrimary: "#26201d",
      textSecondary: "#635650",
      textMuted: "#80726b",
      accent: "#d53c0b",
      accentHover: "#b8340a",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#d53c0b",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(213, 60, 11, 0.18)",
      surfaceMuted: "#f0eeed",
      borderStrong: "#968b87",
      }),
      code: { preset: 'ember-monastery', tokens: resolveCodeThemeTokens('ember-monastery', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#ff6e40",
      background: "#1a120e",
      surface: "#2a1e18",
      surfaceElevated: "#3a2e28",
      surfaceMuted: "#221a14",
      border: "#4a3e38",
      borderStrong: "#6d615a",
      textPrimary: "#f5e6d3",
      textSecondary: "#d4c0a8",
      textMuted: "#9a8878",
      foreground: "#f5e6d3",
      foregroundMuted: "#d4c0a8",
      foregroundSubtle: "#9a8878",
      accentHover: "#ff8c5a",
      accentForeground: "#1a120e",
      success: "#81c784",
      successForeground: "#1a120e",
      warning: "#ffb74d",
      warningForeground: "#1a120e",
      danger: "#e57373",
      dangerForeground: "#1a120e",
      info: "#64b5f6",
      inputBackground: "#3a2e28",
      inputForeground: "#f5e6d3",
      placeholder: "#a69788",
      disabledForeground: "#9a8878",
      buttonPrimaryBackground: "#ff6e40",
      buttonPrimaryForeground: "#1a120e",
      buttonSecondaryBackground: "#3a2e28",
      buttonSecondaryForeground: "#f5e6d3",
      link: "#64b5f6",
      focusRing: "#ff6e40",
      selectionBackground: "#ff6e40",
      selectionForeground: "#1a120e",
      overlay: "rgba(26, 18, 14, 0.7)",
      glow: "rgba(255, 110, 64, 0.25)",
      }),
      code: { preset: 'ember-monastery', tokens: resolveCodeThemeTokens('ember-monastery', 'dark') },
    },
  },
};
