import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_GITHUB_LIGHT: ThemeFamily = {
  schemaVersion: 2,
  id: "github-light",
  name: "Forge GitHub Light",
  aliases: ["builtin-github-light"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#ffffff",
      surface: "#f6f8fa",
      surfaceElevated: "#ffffff",
      border: "#d0d7de",
      textPrimary: "#24292f",
      textSecondary: "#57606a",
      textMuted: "#656d76",
      accent: "#0969da",
      accentHover: "#0550ae",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#7a5200",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#0969da",
      overlay: "rgba(0, 0, 0, 0.25)",
      glow: "rgba(9, 105, 218, 0.18)",
      surfaceMuted: "#ebeef1",
      borderStrong: "#6e7781",
      placeholder: "#57606a",
      disabledForeground: "#6e7781",
      }),
      code: { preset: 'github-light', tokens: resolveCodeThemeTokens('github-light', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#111213",
      surface: "#1b1c1e",
      surfaceElevated: "#242628",
      border: "#3a3d40",
      textPrimary: "#dfe0e2",
      textSecondary: "#abadb0",
      textMuted: "#87898d",
      accent: "#4597f7",
      accentHover: "#6cadf9",
      accentForeground: "#0d1117",
      success: "#3fb950",
      warning: "#d29922",
      danger: "#f85149",
      info: "#58a6ff",
      focusRing: "#4597f7",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(69, 151, 247, 0.25)",
      surfaceMuted: "#161718",
      borderStrong: "#6b7075",
      placeholder: "#8c8e91",
      }),
      code: { preset: 'github-light', tokens: resolveCodeThemeTokens('github-light', 'dark') },
    },
  },
};
