import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_GRUVBOX_DARK: ThemeFamily = {
  schemaVersion: 2,
  id: "gruvbox-dark",
  name: "GruvBox Dark",
  aliases: ["builtin-gruvbox-dark"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f6f6f6",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#d3d2cf",
      textPrimary: "#23221f",
      textSecondary: "#5e5b55",
      textMuted: "#7a7771",
      accent: "#916808",
      accentHover: "#745306",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#916808",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(145, 104, 8, 0.18)",
      surfaceMuted: "#efefee",
      borderStrong: "#8f8d89",
      placeholder: "#77756f",
      }),
      code: { preset: 'gruvbox-dark', tokens: resolveCodeThemeTokens('gruvbox-dark', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#282828",
      surface: "#3c3836",
      surfaceElevated: "#504945",
      border: "#665c54",
      textPrimary: "#ebdbb2",
      textSecondary: "#d5c4a1",
      textMuted: "#928374",
      placeholder: "#c4baac",
      accent: "#fabd2f",
      accentHover: "#d79921",
      accentForeground: "#282828",
      success: "#b8bb26",
      warning: "#fabd2f",
      danger: "#ff6b57",
      info: "#83a598",
      focusRing: "#fabd2f",
      overlay: "rgba(40, 40, 40, 0.6)",
      glow: "rgba(250, 189, 47, 0.25)",
      surfaceMuted: "#32302f",
      borderStrong: "#928374",
      }),
      code: { preset: 'gruvbox-dark', tokens: resolveCodeThemeTokens('gruvbox-dark', 'dark') },
    },
  },
};
