import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_HARBOR_FOG: ThemeFamily = {
  schemaVersion: 2,
  id: "harbor-fog",
  name: "Harbor Fog",
  aliases: ["builtin-harbor-fog"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#207a7a",
      background: "#eef1f4",
      surface: "#e2e8ed",
      surfaceElevated: "#d6dee5",
      surfaceMuted: "#f4f6f8",
      border: "#c8d0d8",
      borderStrong: "#9aa8b4",
      textPrimary: "#1a2a3a",
      textSecondary: "#3f5566",
      textMuted: "#607585",
      foreground: "#1a2a3a",
      foregroundMuted: "#3f5566",
      foregroundSubtle: "#607585",
      accentHover: "#1a6363",
      accentForeground: "#ffffff",
      success: "#2a6e2a",
      successForeground: "#ffffff",
      warning: "#9a6b1a",
      warningForeground: "#ffffff",
      danger: "#a82a2a",
      dangerForeground: "#ffffff",
      info: "#2a5c8a",
      inputBackground: "#d6dee5",
      inputForeground: "#1a2a3a",
      placeholder: "#607585",
      disabledForeground: "#607585",
      buttonPrimaryBackground: "#207a7a",
      buttonPrimaryForeground: "#ffffff",
      buttonSecondaryBackground: "#d6dee5",
      buttonSecondaryForeground: "#1a2a3a",
      link: "#2a5c8a",
      focusRing: "#207a7a",
      selectionBackground: "#207a7a",
      selectionForeground: "#ffffff",
      overlay: "rgba(26, 42, 58, 0.25)",
      glow: "rgba(32, 122, 122, 0.18)",
      }),
      code: { preset: 'harbor-fog', tokens: resolveCodeThemeTokens('harbor-fog', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#0f1215",
      surface: "#181c20",
      surfaceElevated: "#21262c",
      border: "#353d46",
      textPrimary: "#dde0e4",
      textSecondary: "#a6adb4",
      textMuted: "#828a92",
      accent: "#65d7d7",
      accentHover: "#86dfdf",
      accentForeground: "#0d1117",
      success: "#3fb950",
      warning: "#d29922",
      danger: "#f85149",
      info: "#58a6ff",
      focusRing: "#65d7d7",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(101, 215, 215, 0.25)",
      surfaceMuted: "#13171b",
      borderStrong: "#63707e",
      }),
      code: { preset: 'harbor-fog', tokens: resolveCodeThemeTokens('harbor-fog', 'dark') },
    },
  },
};
