import type { Theme } from '../themeTypes';

export const BUILTIN_HARBOR_FOG: Theme = {
  id: "builtin-harbor-fog",
  name: "Harbor Fog",
  mode: "light",
  tokens: {
    accent: "#207a7a",
    background: "#eef1f4",
    surface: "#e2e8ed",
    surfaceElevated: "#d6dee5",
    surfaceMuted: "#f4f6f8",
    border: "#c8d0d8",
    borderStrong: "#9aa8b4",
    textPrimary: "#1a2a3a",
    textSecondary: "#3f5566",
    textMuted: "#607585",
    foreground: "#1a2a3a",
    foregroundMuted: "#3f5566",
    foregroundSubtle: "#607585",
    accentHover: "#1a6363",
    accentForeground: "#ffffff",
    success: "#2a6e2a",
    successForeground: "#ffffff",
    warning: "#9a6b1a",
    warningForeground: "#ffffff",
    danger: "#a82a2a",
    dangerForeground: "#ffffff",
    info: "#2a5c8a",
    inputBackground: "#d6dee5",
    inputForeground: "#1a2a3a",
    placeholder: "#607585",
    disabledForeground: "#607585",
    buttonPrimaryBackground: "#207a7a",
    buttonPrimaryForeground: "#ffffff",
    buttonSecondaryBackground: "#d6dee5",
    buttonSecondaryForeground: "#1a2a3a",
    link: "#2a5c8a",
    focusRing: "#207a7a",
    selectionBackground: "#207a7a",
    selectionForeground: "#ffffff",
    overlay: "rgba(26, 42, 58, 0.25)",
    glow: "rgba(32, 122, 122, 0.18)",
  },
};
