import { BUILTIN_OBSIDIAN_BLOOM } from './obsidianBloom';
import { BUILTIN_HARBOR_FOG } from './harborFog';
import { BUILTIN_CIRCUIT_MINT } from './circuitMint';
import { BUILTIN_AMBER_ARCHIVE } from './amberArchive';
import { BUILTIN_NEON_DUSK } from './neonDusk';
import { BUILTIN_AURORA_BOREAL } from './auroraBoreal';
import { BUILTIN_SAKURA_TERMINAL } from './sakuraTerminal';
import { BUILTIN_BASALT_NOIR } from './basaltNoir';
import { BUILTIN_SOLAR_ASH } from './solarAsh';
import { BUILTIN_CYBER_ORCHID } from './cyberOrchid';
import { BUILTIN_ARCTIC_GLASS } from './arcticGlass';
import { BUILTIN_DESERT_COPPERFIELD } from './desertCopperfield';
import { BUILTIN_TOXIC_LIMEWIRE } from './toxicLimewire';
import { BUILTIN_MIDNIGHT_VELVET } from './midnightVelvet';
import { BUILTIN_PORCELAIN_DAYBREAK } from './porcelainDaybreak';
import { BUILTIN_SYNTHWAVE_HARBOR } from './synthwaveHarbor';
import { BUILTIN_MOSS_CIRCUIT } from './mossCircuit';
import { BUILTIN_EMBER_MONASTERY } from './emberMonastery';
import { BUILTIN_GLACIAL_INK } from './glacialInk';
import { BUILTIN_ULTRAVIOLET_RAIN } from './ultravioletRain';
import { BUILTIN_VENICE } from './venice';
import { BUILTIN_DARK } from './dark';
import { BUILTIN_LIGHT } from './light';
import { BUILTIN_COPPER } from './copper';
import { BUILTIN_DRACULA } from './dracula';
import { BUILTIN_GRUVBOX_DARK } from './gruvboxDark';
import { BUILTIN_ROSEPINE } from './rosepine';
import { BUILTIN_NORD } from './nord';
import { BUILTIN_TOKYO_NIGHT } from './tokyoNight';
import { BUILTIN_CATPPUCCIN } from './catppuccin';
import { BUILTIN_SOLARIZED_DARK } from './solarizedDark';
import { BUILTIN_SOLARIZED_LIGHT } from './solarizedLight';
import { BUILTIN_ONE_DARK } from './oneDark';
import { BUILTIN_MONOKAI } from './monokai';
import { BUILTIN_GITHUB_LIGHT } from './githubLight';
import { BUILTIN_COTTON_CANDY_CONSOLE } from './cottonCandyConsole';
import { BUILTIN_SWEET_NIGHTMARE } from './sweetNightmare';
import { BUILTIN_DUAL_PERSONA } from './dualPersona';
import { BUILTIN_POLAROID_BOARD } from './polaroidBoard';

export {
  BUILTIN_OBSIDIAN_BLOOM,
  BUILTIN_HARBOR_FOG,
  BUILTIN_CIRCUIT_MINT,
  BUILTIN_AMBER_ARCHIVE,
  BUILTIN_NEON_DUSK,
  BUILTIN_AURORA_BOREAL,
  BUILTIN_SAKURA_TERMINAL,
  BUILTIN_BASALT_NOIR,
  BUILTIN_SOLAR_ASH,
  BUILTIN_CYBER_ORCHID,
  BUILTIN_ARCTIC_GLASS,
  BUILTIN_DESERT_COPPERFIELD,
  BUILTIN_TOXIC_LIMEWIRE,
  BUILTIN_MIDNIGHT_VELVET,
  BUILTIN_PORCELAIN_DAYBREAK,
  BUILTIN_SYNTHWAVE_HARBOR,
  BUILTIN_MOSS_CIRCUIT,
  BUILTIN_EMBER_MONASTERY,
  BUILTIN_GLACIAL_INK,
  BUILTIN_ULTRAVIOLET_RAIN,
  BUILTIN_VENICE,
  BUILTIN_DARK,
  BUILTIN_LIGHT,
  BUILTIN_COPPER,
  BUILTIN_DRACULA,
  BUILTIN_GRUVBOX_DARK,
  BUILTIN_ROSEPINE,
  BUILTIN_NORD,
  BUILTIN_TOKYO_NIGHT,
  BUILTIN_CATPPUCCIN,
  BUILTIN_SOLARIZED_DARK,
  BUILTIN_SOLARIZED_LIGHT,
  BUILTIN_ONE_DARK,
  BUILTIN_MONOKAI,
  BUILTIN_GITHUB_LIGHT,
  BUILTIN_COTTON_CANDY_CONSOLE,
  BUILTIN_SWEET_NIGHTMARE,
  BUILTIN_DUAL_PERSONA,
  BUILTIN_POLAROID_BOARD,
};

export const BUILTIN_THEMES = [
  BUILTIN_OBSIDIAN_BLOOM,
  BUILTIN_HARBOR_FOG,
  BUILTIN_CIRCUIT_MINT,
  BUILTIN_AMBER_ARCHIVE,
  BUILTIN_NEON_DUSK,
  BUILTIN_AURORA_BOREAL,
  BUILTIN_SAKURA_TERMINAL,
  BUILTIN_BASALT_NOIR,
  BUILTIN_SOLAR_ASH,
  BUILTIN_CYBER_ORCHID,
  BUILTIN_ARCTIC_GLASS,
  BUILTIN_DESERT_COPPERFIELD,
  BUILTIN_TOXIC_LIMEWIRE,
  BUILTIN_MIDNIGHT_VELVET,
  BUILTIN_PORCELAIN_DAYBREAK,
  BUILTIN_SYNTHWAVE_HARBOR,
  BUILTIN_MOSS_CIRCUIT,
  BUILTIN_EMBER_MONASTERY,
  BUILTIN_GLACIAL_INK,
  BUILTIN_ULTRAVIOLET_RAIN,
  BUILTIN_VENICE,
  BUILTIN_DARK,
  BUILTIN_LIGHT,
  BUILTIN_COPPER,
  BUILTIN_DRACULA,
  BUILTIN_GRUVBOX_DARK,
  BUILTIN_ROSEPINE,
  BUILTIN_NORD,
  BUILTIN_TOKYO_NIGHT,
  BUILTIN_CATPPUCCIN,
  BUILTIN_SOLARIZED_DARK,
  BUILTIN_SOLARIZED_LIGHT,
  BUILTIN_ONE_DARK,
  BUILTIN_MONOKAI,
  BUILTIN_GITHUB_LIGHT,
  BUILTIN_COTTON_CANDY_CONSOLE,
  BUILTIN_SWEET_NIGHTMARE,
  BUILTIN_DUAL_PERSONA,
  BUILTIN_POLAROID_BOARD,
];

export const DEFAULT_THEME = BUILTIN_VENICE;
