import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_LIGHT: ThemeFamily = {
  schemaVersion: 2,
  id: "light",
  name: "Forge Daylight",
  aliases: ["builtin-light"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f6f8fa",
      surface: "#ffffff",
      surfaceElevated: "#fcfcfc",
      border: "#d0d7de",
      textPrimary: "#1f2328",
      textSecondary: "#57606a",
      textMuted: "#656d76",
      accent: "#0969da",
      accentHover: "#0860c4",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#7a5200",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#0969da",
      overlay: "rgba(0,0,0,0.4)",
      glow: "rgba(9,105,218,0.18)",
      surfaceMuted: "#eef1f4",
      borderStrong: "#878f99",
      placeholder: "#57606a",
      disabledForeground: "#6e7781",
      }),
      code: { preset: 'light', tokens: resolveCodeThemeTokens('light', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#0d1117",
      surface: "#161b22",
      surfaceElevated: "#1c2330",
      border: "#2a3140",
      textPrimary: "#d0d7de",
      textSecondary: "#9aa7b8",
      textMuted: "#808b9b",
      accent: "#58a6ff",
      accentHover: "#79b8ff",
      accentForeground: "#0d1117",
      success: "#3fb950",
      warning: "#d29922",
      danger: "#f85149",
      info: "#58a6ff",
      focusRing: "#58a6ff",
      overlay: "rgba(0,0,0,0.6)",
      glow: "rgba(88,166,255,0.2)",
      surfaceMuted: "#11161d",
      borderStrong: "#6b7686",
      placeholder: "#808b9b",
      disabledForeground: "#586270",
      }),
      code: { preset: 'light', tokens: resolveCodeThemeTokens('light', 'dark') },
    },
  },
};
