import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_MIDNIGHT_VELVET: ThemeFamily = {
  schemaVersion: 2,
  id: "midnight-velvet",
  name: "Midnight Velvet",
  aliases: ["builtin-midnight-velvet"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f5f5f7",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#ccced7",
      textPrimary: "#1b1e28",
      textSecondary: "#4b5268",
      textMuted: "#666d85",
      accent: "#9341a9",
      accentHover: "#7f3993",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#9341a9",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(147, 65, 169, 0.18)",
      surfaceMuted: "#edeef0",
      borderStrong: "#888e9f",
      }),
      code: { preset: 'midnight-velvet', tokens: resolveCodeThemeTokens('midnight-velvet', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#d8b4e2",
      background: "#0a0e1a",
      surface: "#14182e",
      surfaceElevated: "#1e2240",
      surfaceMuted: "#101428",
      border: "#2e3250",
      borderStrong: "#5c5f7a",
      textPrimary: "#f5e6e8",
      textSecondary: "#d0b8c0",
      textMuted: "#908090",
      foreground: "#f5e6e8",
      foregroundMuted: "#d0b8c0",
      foregroundSubtle: "#908090",
      accentHover: "#e8c8f2",
      accentForeground: "#0a0e1a",
      success: "#a5d6a7",
      successForeground: "#0a0e1a",
      warning: "#ffcc80",
      warningForeground: "#0a0e1a",
      danger: "#ef9a9a",
      dangerForeground: "#0a0e1a",
      info: "#90caf9",
      inputBackground: "#1e2240",
      inputForeground: "#f5e6e8",
      placeholder: "#908090",
      disabledForeground: "#908090",
      buttonPrimaryBackground: "#d8b4e2",
      buttonPrimaryForeground: "#0a0e1a",
      buttonSecondaryBackground: "#1e2240",
      buttonSecondaryForeground: "#f5e6e8",
      link: "#90caf9",
      focusRing: "#d8b4e2",
      selectionBackground: "#d8b4e2",
      selectionForeground: "#0a0e1a",
      overlay: "rgba(10, 14, 26, 0.7)",
      glow: "rgba(216, 180, 226, 0.25)",
      }),
      code: { preset: 'midnight-velvet', tokens: resolveCodeThemeTokens('midnight-velvet', 'dark') },
    },
  },
};
