import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_MIDNIGHT_COBALT: ThemeFamily = {
  schemaVersion: 2,
  id: "midnight-cobalt",
  name: "Midnight Cobalt",
  aliases: ["builtin-midnight-cobalt","midnight-cobalt"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f5f6f7",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#cbcfd7",
      textPrimary: "#1a1e28",
      textSecondary: "#4a5369",
      textMuted: "#646f86",
      accent: "#1c57ce",
      accentHover: "#194cb3",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#1c57ce",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(28, 87, 206, 0.18)",
      surfaceMuted: "#edeef0",
      borderStrong: "#888fa0",
      }),
      code: { preset: 'midnight-cobalt', tokens: resolveCodeThemeTokens('midnight-cobalt', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#070b14",
      surface: "#0f1626",
      surfaceElevated: "#17223b",
      border: "#2a3b5c",
      textPrimary: "#e6f0ff",
      textSecondary: "#94a7c7",
      textMuted: "#687b9c",
      accent: "#1e5cd9",
      accentHover: "#2a6df0",
      accentForeground: "#ffffff",
      success: "#1b5e20",
      warning: "#9e4a00",
      danger: "#b71c1c",
      info: "#4c8bf5",
      focusRing: "#1e5cd9",
      overlay: "rgba(0,0,0,0.65)",
      glow: "rgba(30, 92, 217, 0.3)",
      surfaceMuted: "#0b101c",
      borderStrong: "#3d527a",
      dangerForeground: "#ffffff",
      warningForeground: "#ffffff",
      successForeground: "#ffffff",
      }),
      code: { preset: 'midnight-cobalt', tokens: resolveCodeThemeTokens('midnight-cobalt', 'dark') },
    },
  },
};
