import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_MONOKAI: ThemeFamily = {
  schemaVersion: 2,
  id: "monokai",
  name: "Forge Monokai",
  aliases: ["builtin-monokai"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f6f6f6",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#d2d3cf",
      textPrimary: "#22231f",
      textSecondary: "#5b5e55",
      textMuted: "#777a71",
      accent: "#597d11",
      accentHover: "#46630e",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#597d11",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(89, 125, 17, 0.18)",
      surfaceMuted: "#efefee",
      borderStrong: "#959790",
      }),
      code: { preset: 'monokai', tokens: resolveCodeThemeTokens('monokai', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#272822",
      surface: "#383830",
      surfaceElevated: "#49483e",
      border: "#6b6b6b",
      textPrimary: "#f8f8f2",
      textSecondary: "#a6a48a",
      textMuted: "#989681",
      accent: "#a6e22e",
      accentHover: "#f92672",
      accentForeground: "#272822",
      success: "#a6e22e",
      warning: "#e6db74",
      danger: "#e6004c",
      dangerForeground: "#ffffff",
      info: "#66d9ef",
      focusRing: "#a6e22e",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(166, 226, 46, 0.25)",
      surfaceMuted: "#2c2d26",
      borderStrong: "#f8f8f2",
      }),
      code: { preset: 'monokai', tokens: resolveCodeThemeTokens('monokai', 'dark') },
    },
  },
};
