import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_MOSS_CIRCUIT: ThemeFamily = {
  schemaVersion: 2,
  id: "moss-circuit",
  name: "Moss Circuit",
  aliases: ["builtin-moss-circuit"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f6f7f6",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#ced4d0",
      textPrimary: "#1e2420",
      textSecondary: "#526056",
      textMuted: "#6e7d72",
      accent: "#587f2f",
      accentHover: "#486826",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#587f2f",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(88, 127, 47, 0.18)",
      surfaceMuted: "#eeefee",
      borderStrong: "#86908a",
      }),
      code: { preset: 'moss-circuit', tokens: resolveCodeThemeTokens('moss-circuit', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#7cb342",
      background: "#0d140f",
      surface: "#1a231d",
      surfaceElevated: "#27322a",
      surfaceMuted: "#131c15",
      border: "#374238",
      borderStrong: "#5a655b",
      textPrimary: "#e8f5e9",
      textSecondary: "#b8d0b0",
      textMuted: "#789070",
      foreground: "#e8f5e9",
      foregroundMuted: "#b8d0b0",
      foregroundSubtle: "#789070",
      accentHover: "#8bc34a",
      accentForeground: "#0d140f",
      success: "#66bb6a",
      successForeground: "#0d140f",
      warning: "#ffca28",
      warningForeground: "#0d140f",
      danger: "#ef5350",
      dangerForeground: "#0d140f",
      info: "#29b6f6",
      inputBackground: "#27322a",
      inputForeground: "#e8f5e9",
      placeholder: "#789070",
      disabledForeground: "#789070",
      buttonPrimaryBackground: "#7cb342",
      buttonPrimaryForeground: "#0d140f",
      buttonSecondaryBackground: "#27322a",
      buttonSecondaryForeground: "#e8f5e9",
      link: "#29b6f6",
      focusRing: "#7cb342",
      selectionBackground: "#7cb342",
      selectionForeground: "#0d140f",
      overlay: "rgba(13, 20, 15, 0.7)",
      glow: "rgba(124, 179, 66, 0.25)",
      }),
      code: { preset: 'moss-circuit', tokens: resolveCodeThemeTokens('moss-circuit', 'dark') },
    },
  },
};
