import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_NEON_DUSK: ThemeFamily = {
  schemaVersion: 2,
  id: "neon-dusk",
  name: "Neon Dusk",
  aliases: ["builtin-neon-dusk"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f5f5f7",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#cdccd7",
      textPrimary: "#1d1b28",
      textSecondary: "#504b67",
      textMuted: "#6b6685",
      accent: "#be13d8",
      accentHover: "#a510bc",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#be13d8",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(190, 19, 216, 0.18)",
      surfaceMuted: "#ededf0",
      borderStrong: "#8c899f",
      }),
      code: { preset: 'neon-dusk', tokens: resolveCodeThemeTokens('neon-dusk', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#d946ef",
      background: "#0f0c1f",
      surface: "#1a1630",
      surfaceElevated: "#252146",
      surfaceMuted: "#14122a",
      border: "#36315c",
      borderStrong: "#544d88",
      textPrimary: "#f0eef5",
      textSecondary: "#c9c4e0",
      textMuted: "#8f88b0",
      foreground: "#f0eef5",
      foregroundMuted: "#c9c4e0",
      foregroundSubtle: "#8f88b0",
      accentHover: "#e46ef5",
      accentForeground: "#0f0c1f",
      success: "#5de8a2",
      successForeground: "#0f0c1f",
      warning: "#f5c842",
      warningForeground: "#0f0c1f",
      danger: "#f56464",
      dangerForeground: "#0f0c1f",
      info: "#5ee1f5",
      inputBackground: "#252146",
      inputForeground: "#f0eef5",
      placeholder: "#8f88b0",
      disabledForeground: "#8f88b0",
      buttonPrimaryBackground: "#d946ef",
      buttonPrimaryForeground: "#0f0c1f",
      buttonSecondaryBackground: "#252146",
      buttonSecondaryForeground: "#f0eef5",
      link: "#5ee1f5",
      focusRing: "#d946ef",
      selectionBackground: "#d946ef",
      selectionForeground: "#0f0c1f",
      overlay: "rgba(15, 12, 31, 0.7)",
      glow: "rgba(217, 70, 239, 0.25)",
      }),
      code: { preset: 'neon-dusk', tokens: resolveCodeThemeTokens('neon-dusk', 'dark') },
    },
  },
};
