import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_NORD: ThemeFamily = {
  schemaVersion: 2,
  id: "nord",
  name: "Forge Nord",
  aliases: ["builtin-nord"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f6f6f7",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#cfd0d3",
      textPrimary: "#1f2024",
      textSecondary: "#54575f",
      textMuted: "#70737b",
      accent: "#37788b",
      accentHover: "#2e6575",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#37788b",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(55, 120, 139, 0.18)",
      surfaceMuted: "#eeeeef",
      borderStrong: "#8c8d93",
      }),
      code: { preset: 'nord', tokens: resolveCodeThemeTokens('nord', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#2E3440",
      surface: "#3B4252",
      surfaceElevated: "#434C5E",
      border: "#4C566A",
      textPrimary: "#D8DEE9",
      textSecondary: "#B0B9C6",
      textMuted: "#81A1C1",
      accent: "#88C0D0",
      accentHover: "#8FBCBB",
      accentForeground: "#2E3440",
      success: "#A3BE8C",
      warning: "#EBCB8B",
      danger: "#ff6b6b",
      info: "#81A1C1",
      focusRing: "#88C0D0",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(136, 192, 208, 0.25)",
      surfaceMuted: "#2A2F3A",
      borderStrong: "#D8DEE9",
      placeholder: "#aac0d5",
      }),
      code: { preset: 'nord', tokens: resolveCodeThemeTokens('nord', 'dark') },
    },
  },
};
