import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_OBSIDIAN_EMBER: ThemeFamily = {
  schemaVersion: 2,
  id: "obsidian-ember",
  name: "Obsidian Ember",
  aliases: ["builtin-obsidian-ember","obsidian-ember"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f6f6f6",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#d3d0cf",
      textPrimary: "#23201f",
      textSecondary: "#5e5755",
      textMuted: "#7a7371",
      accent: "#ce4112",
      accentHover: "#b23810",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#ce4112",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(206, 65, 18, 0.18)",
      surfaceMuted: "#efeeee",
      borderStrong: "#979290",
      }),
      code: { preset: 'obsidian-ember', tokens: resolveCodeThemeTokens('obsidian-ember', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#121212",
      surface: "#1c1c1c",
      surfaceElevated: "#262626",
      border: "#333333",
      textPrimary: "#eae4d9",
      textSecondary: "#a09a90",
      textMuted: "#706b64",
      accent: "#b83a10",
      accentHover: "#f0642f",
      accentForeground: "#ffffff",
      success: "#1b5e20",
      warning: "#9e4a00",
      danger: "#b71c1c",
      info: "#8c8375",
      focusRing: "#d95321",
      overlay: "rgba(0,0,0,0.7)",
      glow: "rgba(217, 83, 33, 0.25)",
      surfaceMuted: "#161616",
      borderStrong: "#4c4c4c",
      dangerForeground: "#ffffff",
      warningForeground: "#ffffff",
      successForeground: "#ffffff",
      }),
      code: { preset: 'obsidian-ember', tokens: resolveCodeThemeTokens('obsidian-ember', 'dark') },
    },
  },
};
