import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_OBSIDIAN_BLOOM: ThemeFamily = {
  schemaVersion: 2,
  id: "obsidian-bloom",
  name: "Obsidian Bloom",
  aliases: ["builtin-obsidian-bloom"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f6f5f7",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#d2ced5",
      textPrimary: "#221d25",
      textSecondary: "#5c5062",
      textMuted: "#786b7f",
      accent: "#c2294a",
      accentHover: "#a82440",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#c2294a",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(194, 41, 74, 0.18)",
      surfaceMuted: "#efedf0",
      borderStrong: "#928a97",
      }),
      code: { preset: 'obsidian-bloom', tokens: resolveCodeThemeTokens('obsidian-bloom', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#e06c85",
      background: "#0f0a12",
      surface: "#1a141c",
      surfaceElevated: "#252026",
      surfaceMuted: "#140f15",
      border: "#332a35",
      borderStrong: "#685c66",
      textPrimary: "#f0e8f0",
      textSecondary: "#c8bac8",
      textMuted: "#8f7d8f",
      foreground: "#f0e8f0",
      foregroundMuted: "#c8bac8",
      foregroundSubtle: "#8f7d8f",
      accentHover: "#e88c9f",
      accentForeground: "#0f0a12",
      success: "#5a9e5a",
      successForeground: "#0f0a12",
      warning: "#d4a04a",
      warningForeground: "#0f0a12",
      danger: "#e55c5c",
      dangerForeground: "#0f0a12",
      info: "#8bb8e8",
      inputBackground: "#252026",
      inputForeground: "#f0e8f0",
      placeholder: "#8f7d8f",
      disabledForeground: "#8f7d8f",
      buttonPrimaryBackground: "#e06c85",
      buttonPrimaryForeground: "#0f0a12",
      buttonSecondaryBackground: "#252026",
      buttonSecondaryForeground: "#f0e8f0",
      link: "#8bb8e8",
      focusRing: "#e06c85",
      selectionBackground: "#e06c85",
      selectionForeground: "#0f0a12",
      overlay: "rgba(15, 10, 18, 0.7)",
      glow: "rgba(224, 108, 133, 0.25)",
      }),
      code: { preset: 'obsidian-bloom', tokens: resolveCodeThemeTokens('obsidian-bloom', 'dark') },
    },
  },
};
