import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_ONE_DARK: ThemeFamily = {
  schemaVersion: 2,
  id: "one-dark",
  name: "Forge One Dark",
  aliases: ["builtin-one-dark"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f6f6f6",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#cfd1d3",
      textPrimary: "#1f2023",
      textSecondary: "#55585e",
      textMuted: "#71747a",
      accent: "#1474c3",
      accentHover: "#1163a7",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#1474c3",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(20, 116, 195, 0.18)",
      surfaceMuted: "#eeeeef",
      borderStrong: "#8b8d91",
      }),
      code: { preset: 'one-dark', tokens: resolveCodeThemeTokens('one-dark', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#282c34",
      surface: "#353b45",
      surfaceElevated: "#3e4451",
      border: "#4b5263",
      textPrimary: "#abb2bf",
      textSecondary: "#9ca0aa",
      textMuted: "#91969e",
      accent: "#61afef",
      accentHover: "#528bcc",
      accentForeground: "#282c34",
      success: "#98c379",
      warning: "#e5c07b",
      danger: "#cf222e",
      dangerForeground: "#ffffff",
      info: "#56b6c2",
      focusRing: "#61afef",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(97, 175, 239, 0.25)",
      surfaceMuted: "#2c313a",
      borderStrong: "#abb2bf",
      }),
      code: { preset: 'one-dark', tokens: resolveCodeThemeTokens('one-dark', 'dark') },
    },
  },
};
