import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_POLAROID_BOARD: ThemeFamily = {
  schemaVersion: 2,
  id: "polaroid-board",
  name: "Polaroid Board",
  aliases: ["builtin-polaroid-board"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#9EBFD0",
      background: "#D8B09E",
      surface: "#F3EDEB",
      surfaceElevated: "#FFF9F5",
      surfaceMuted: "#EADAD5",
      border: "#BA7D6E",
      borderStrong: "#795b5d",
      textPrimary: "#291A1E",
      textSecondary: "#442E35",
      textMuted: "#543941",
      foreground: "#291A1E",
      foregroundMuted: "#442E35",
      foregroundSubtle: "#543941",
      accentHover: "#86ADBE",
      accentForeground: "#1A1012",
      success: "#287557",
      successForeground: "#FFFFFF",
      warning: "#A35324",
      warningForeground: "#FFFFFF",
      danger: "#AA5B6E",
      dangerForeground: "#FFFFFF",
      info: "#4A5F73",
      inputBackground: "#FFF9F5",
      inputForeground: "#291A1E",
      placeholder: "#543941",
      disabledForeground: "#543941",
      buttonPrimaryBackground: "#9EBFD0",
      buttonPrimaryForeground: "#1A1012",
      buttonSecondaryBackground: "#EADAD5",
      buttonSecondaryForeground: "#291A1E",
      link: "#304c5b",
      focusRing: "#675B6E",
      selectionBackground: "#CDD7DD",
      selectionForeground: "#291A1E",
      overlay: "rgba(41, 26, 30, 0.45)",
      glow: "rgba(158, 191, 208, 0.25)",
      }),
      code: { preset: 'polaroid-board', tokens: resolveCodeThemeTokens('polaroid-board', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#16100d",
      surface: "#221a16",
      surfaceElevated: "#2e231e",
      border: "#493931",
      textPrimary: "#e5dfdc",
      textSecondary: "#b8aaa3",
      textMuted: "#95857e",
      accent: "#72acca",
      accentHover: "#90bed5",
      accentForeground: "#0d1117",
      success: "#3fb950",
      warning: "#d29922",
      danger: "#f85149",
      info: "#58a6ff",
      focusRing: "#72acca",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(114, 172, 202, 0.25)",
      surfaceMuted: "#1d1511",
      borderStrong: "#84695d",
      placeholder: "#9a8a83",
      }),
      code: { preset: 'polaroid-board', tokens: resolveCodeThemeTokens('polaroid-board', 'dark') },
    },
  },
};
