import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_PORCELAIN_DAYBREAK: ThemeFamily = {
  schemaVersion: 2,
  id: "porcelain-daybreak",
  name: "Porcelain Daybreak",
  aliases: ["builtin-porcelain-daybreak"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#ffab91",
      background: "#fafafa",
      surface: "#f0f0f0",
      surfaceElevated: "#e6e6e6",
      surfaceMuted: "#f5f5f5",
      border: "#dcdcdc",
      borderStrong: "#8b9193",
      textPrimary: "#37474f",
      textSecondary: "#5a6a72",
      textMuted: "#6b7d85",
      foreground: "#37474f",
      foregroundMuted: "#5a6a72",
      foregroundSubtle: "#6b7d85",
      accentHover: "#f59580",
      accentForeground: "#37474f",
      success: "#2e7d32",
      successForeground: "#ffffff",
      warning: "#ffb74d",
      warningForeground: "#37474f",
      danger: "#d32f2f",
      dangerForeground: "#ffffff",
      info: "#64b5f6",
      inputBackground: "#e6e6e6",
      inputForeground: "#37474f",
      placeholder: "#6b7d85",
      disabledForeground: "#6b7d85",
      buttonPrimaryBackground: "#ffab91",
      buttonPrimaryForeground: "#37474f",
      buttonSecondaryBackground: "#e6e6e6",
      buttonSecondaryForeground: "#37474f",
      link: "#0c75ca",
      focusRing: "#a84a39",
      selectionBackground: "#ffab91",
      selectionForeground: "#37474f",
      overlay: "rgba(55, 71, 79, 0.25)",
      glow: "rgba(255, 171, 145, 0.18)",
      }),
      code: { preset: 'porcelain-daybreak', tokens: resolveCodeThemeTokens('porcelain-daybreak', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#131111",
      surface: "#1e1b1b",
      surfaceElevated: "#282524",
      border: "#403c3a",
      textPrimary: "#e2e0df",
      textSecondary: "#b0acab",
      textMuted: "#8d8887",
      accent: "#fa6e42",
      accentHover: "#fb8c6a",
      accentForeground: "#0d1117",
      success: "#3fb950",
      warning: "#d29922",
      danger: "#f85149",
      info: "#58a6ff",
      focusRing: "#fa6e42",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(250, 110, 66, 0.25)",
      surfaceMuted: "#181616",
      borderStrong: "#756e6b",
      }),
      code: { preset: 'porcelain-daybreak', tokens: resolveCodeThemeTokens('porcelain-daybreak', 'dark') },
    },
  },
};
