import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_PORCELAIN_SKY: ThemeFamily = {
  schemaVersion: 2,
  id: "porcelain-sky",
  name: "Porcelain Sky",
  aliases: ["builtin-porcelain-sky","porcelain-sky"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f8fafc",
      surface: "#eff4f9",
      surfaceElevated: "#ffffff",
      border: "#cbd5e1",
      textPrimary: "#1e293b",
      textSecondary: "#475569",
      textMuted: "#64748b",
      accent: "#2563eb",
      accentHover: "#1d4ed8",
      accentForeground: "#ffffff",
      success: "#1b5e20",
      warning: "#9e4a00",
      danger: "#b71c1c",
      info: "#3b82f6",
      focusRing: "#3b82f6",
      overlay: "rgba(255,255,255,0.7)",
      glow: "rgba(37, 99, 235, 0.2)",
      surfaceMuted: "#e2e8f0",
      borderStrong: "#94a3b8",
      warningForeground: "#ffffff",
      successForeground: "#ffffff",
      dangerForeground: "#ffffff",
      }),
      code: { preset: 'porcelain-sky', tokens: resolveCodeThemeTokens('porcelain-sky', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#0d1216",
      surface: "#161c22",
      surfaceElevated: "#1e262e",
      border: "#313d49",
      textPrimary: "#dce0e5",
      textSecondary: "#a3adb8",
      textMuted: "#7e8a95",
      accent: "#4d80ef",
      accentHover: "#739bf2",
      accentForeground: "#0d1117",
      success: "#3fb950",
      warning: "#d29922",
      danger: "#f85149",
      info: "#58a6ff",
      focusRing: "#4d80ef",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(77, 128, 239, 0.25)",
      surfaceMuted: "#11171d",
      borderStrong: "#5d7084",
      }),
      code: { preset: 'porcelain-sky', tokens: resolveCodeThemeTokens('porcelain-sky', 'dark') },
    },
  },
};
