import type { Theme } from '../themeTypes';

export const BUILTIN_PORCELAIN_DAYBREAK: Theme = {
  id: "builtin-porcelain-daybreak",
  name: "Porcelain Daybreak",
  mode: "light",
  tokens: {
    accent: "#ffab91",
    background: "#fafafa",
    surface: "#f0f0f0",
    surfaceElevated: "#e6e6e6",
    surfaceMuted: "#f5f5f5",
    border: "#dcdcdc",
    borderStrong: "#bcbcbc",
    textPrimary: "#37474f",
    textSecondary: "#5a6a72",
    textMuted: "#8a9aa2",
    foreground: "#37474f",
    foregroundMuted: "#5a6a72",
    foregroundSubtle: "#8a9aa2",
    accentHover: "#f59580",
    accentForeground: "#ffffff",
    success: "#66bb6a",
    successForeground: "#ffffff",
    warning: "#ffb74d",
    warningForeground: "#37474f",
    danger: "#e57373",
    dangerForeground: "#ffffff",
    info: "#64b5f6",
    inputBackground: "#e6e6e6",
    inputForeground: "#37474f",
    placeholder: "#8a9aa2",
    disabledForeground: "#8a9aa2",
    buttonPrimaryBackground: "#ffab91",
    buttonPrimaryForeground: "#ffffff",
    buttonSecondaryBackground: "#e6e6e6",
    buttonSecondaryForeground: "#37474f",
    link: "#64b5f6",
    focusRing: "#ffab91",
    selectionBackground: "#ffab91",
    selectionForeground: "#ffffff",
    overlay: "rgba(55, 71, 79, 0.25)",
    glow: "rgba(255, 171, 145, 0.18)",
  },
};
