import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_ROSEPINE: ThemeFamily = {
  schemaVersion: 2,
  id: "rosepine",
  name: "Rosepine",
  aliases: ["builtin-rosepine"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f6f5f7",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#cfced4",
      textPrimary: "#1f1e24",
      textSecondary: "#545260",
      textMuted: "#706e7d",
      accent: "#b63a35",
      accentHover: "#9e322e",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#b63a35",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(182, 58, 53, 0.18)",
      surfaceMuted: "#eeeeef",
      borderStrong: "#908e9a",
      }),
      code: { preset: 'rosepine', tokens: resolveCodeThemeTokens('rosepine', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#191724",
      surface: "#1f1d2e",
      surfaceElevated: "#26233a",
      border: "#403d52",
      textPrimary: "#e0def4",
      textSecondary: "#908caa",
      textMuted: "#6e6a86",
      accent: "#ebbcba",
      accentHover: "#31748f",
      accentForeground: "#191724",
      success: "#9ccfd8",
      warning: "#f6c177",
      danger: "#eb6f92",
      info: "#c4a7e7",
      focusRing: "#ebbcba",
      overlay: "rgba(25, 23, 36, 0.7)",
      glow: "rgba(235, 188, 186, 0.2)",
      surfaceMuted: "#211f30",
      borderStrong: "#6e6a86",
      }),
      code: { preset: 'rosepine', tokens: resolveCodeThemeTokens('rosepine', 'dark') },
    },
  },
};
