import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_SAKURA_TERMINAL: ThemeFamily = {
  schemaVersion: 2,
  id: "sakura-terminal",
  name: "Sakura Terminal",
  aliases: ["builtin-sakura-terminal"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f7f6f6",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#d3cfd2",
      textPrimary: "#241e23",
      textSecondary: "#5f535c",
      textMuted: "#7c6f78",
      accent: "#df0c31",
      accentHover: "#c20a2b",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#df0c31",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(223, 12, 49, 0.18)",
      surfaceMuted: "#efeeef",
      borderStrong: "#998f96",
      }),
      code: { preset: 'sakura-terminal', tokens: resolveCodeThemeTokens('sakura-terminal', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#ff8fa3",
      background: "#1a1218",
      surface: "#2a2028",
      surfaceElevated: "#3a3038",
      surfaceMuted: "#221a20",
      border: "#4a3a48",
      borderStrong: "#6a5a68",
      textPrimary: "#ffe4ec",
      textSecondary: "#d4b0c0",
      textMuted: "#9a7a8a",
      foreground: "#ffe4ec",
      foregroundMuted: "#d4b0c0",
      foregroundSubtle: "#9a7a8a",
      accentHover: "#ffb3c1",
      accentForeground: "#1a1218",
      success: "#a8e6cf",
      successForeground: "#1a1218",
      warning: "#ffd3b6",
      warningForeground: "#1a1218",
      danger: "#ff8b94",
      dangerForeground: "#1a1218",
      info: "#c7ceea",
      inputBackground: "#3a3038",
      inputForeground: "#ffe4ec",
      placeholder: "#9a7a8a",
      disabledForeground: "#9a7a8a",
      buttonPrimaryBackground: "#ff8fa3",
      buttonPrimaryForeground: "#1a1218",
      buttonSecondaryBackground: "#3a3038",
      buttonSecondaryForeground: "#ffe4ec",
      link: "#c7ceea",
      focusRing: "#ff8fa3",
      selectionBackground: "#ff8fa3",
      selectionForeground: "#1a1218",
      overlay: "rgba(26, 18, 24, 0.7)",
      glow: "rgba(255, 143, 163, 0.25)",
      }),
      code: { preset: 'sakura-terminal', tokens: resolveCodeThemeTokens('sakura-terminal', 'dark') },
    },
  },
};
