import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_SANDSTONE: ThemeFamily = {
  schemaVersion: 2,
  id: "sandstone",
  name: "Sandstone",
  aliases: ["builtin-sandstone"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#fcfaf8",
      surface: "#f3ece4",
      surfaceElevated: "#faf7f2",
      border: "#d6cec4",
      textPrimary: "#3d3935",
      textSecondary: "#66605a",
      textMuted: "#8a837c",
      accent: "#b85c3b",
      accentHover: "#9c4b2e",
      accentForeground: "#ffffff",
      success: "#1b5e20",
      warning: "#9e4a00",
      danger: "#b71c1c",
      info: "#826e5d",
      focusRing: "#b85c3b",
      overlay: "rgba(252,250,248,0.75)",
      glow: "rgba(184, 92, 59, 0.2)",
      surfaceMuted: "#e6ded5",
      borderStrong: "#978f86",
      placeholder: "#766f69",
      warningForeground: "#ffffff",
      successForeground: "#ffffff",
      dangerForeground: "#ffffff",
      }),
      code: { preset: 'sandstone', tokens: resolveCodeThemeTokens('sandstone', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#16120d",
      surface: "#221c16",
      surfaceElevated: "#2e261e",
      border: "#493d31",
      textPrimary: "#e5e0dc",
      textSecondary: "#b8ada3",
      textMuted: "#958a7e",
      accent: "#d0876c",
      accentHover: "#daa08b",
      accentForeground: "#0d1117",
      success: "#3fb950",
      warning: "#d29922",
      danger: "#f85149",
      info: "#58a6ff",
      focusRing: "#d0876c",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(208, 135, 108, 0.25)",
      surfaceMuted: "#1d1711",
      borderStrong: "#84705d",
      placeholder: "#988e82",
      }),
      code: { preset: 'sandstone', tokens: resolveCodeThemeTokens('sandstone', 'dark') },
    },
  },
};
