import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_SOLARIZED: ThemeFamily = {
  schemaVersion: 2,
  id: 'solarized',
  name: 'Forge Solarized',
  aliases: ['builtin-solarized', 'builtin-solarized-dark', 'builtin-solarized-light'],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
        background: '#fdf6e3',
        surface: '#eee8d5',
        surfaceElevated: '#ffffff',
        border: '#93a1a1',
        textPrimary: '#073642',
        textSecondary: '#586e75',
        textMuted: '#5f7378',
        accent: '#cb4b16',
        accentHover: '#dc322f',
        accentForeground: '#ffffff',
        success: '#556b00',
        warning: '#8f6a00',
        danger: '#c52c29',
        info: '#268bd2',
        link: '#2075b2',
        focusRing: '#cb4b16',
        overlay: 'rgba(0, 0, 0, 0.25)',
        glow: 'rgba(203, 75, 22, 0.18)',
        surfaceMuted: '#e6dfc8',
        borderStrong: '#586e75',
      }),
      code: { preset: 'solarized', tokens: resolveCodeThemeTokens('solarized', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
        background: '#002b36',
        surface: '#073642',
        surfaceElevated: '#0a3c49',
        border: '#657b83',
        textPrimary: '#eee8d5',
        textSecondary: '#93a1a1',
        textMuted: '#839496',
        accent: '#b58900',
        accentHover: '#cb4b16',
        accentForeground: '#002b36',
        success: '#859900',
        warning: '#b58900',
        danger: '#ff5252',
        info: '#268bd2',
        link: '#3094da',
        focusRing: '#b58900',
        overlay: 'rgba(0, 0, 0, 0.6)',
        glow: 'rgba(181, 137, 0, 0.25)',
        surfaceMuted: '#00313f',
        borderStrong: '#93a1a1',
      }),
      code: { preset: 'solarized', tokens: resolveCodeThemeTokens('solarized', 'dark') },
    },
  },
};
