import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_SOLAR_ASH: ThemeFamily = {
  schemaVersion: 2,
  id: "solar-ash",
  name: "Solar Ash",
  aliases: ["builtin-solar-ash"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#c9a227",
      background: "#f5f0eb",
      surface: "#e8e4df",
      surfaceElevated: "#dbd7d2",
      surfaceMuted: "#eeeae5",
      border: "#d0ccc7",
      borderStrong: "#b0aca7",
      textPrimary: "#2c2825",
      textSecondary: "#5a5653",
      textMuted: "#8a8682",
      foreground: "#2c2825",
      foregroundMuted: "#5a5653",
      foregroundSubtle: "#8a8682",
      accentHover: "#a88a20",
      accentForeground: "#2c2825",
      success: "#3f6b22",
      successForeground: "#ffffff",
      warning: "#f9a825",
      warningForeground: "#2c2825",
      danger: "#c62828",
      dangerForeground: "#ffffff",
      info: "#1565c0",
      inputBackground: "#dbd7d2",
      inputForeground: "#2c2825",
      placeholder: "#8a8682",
      disabledForeground: "#8a8682",
      buttonPrimaryBackground: "#c9a227",
      buttonPrimaryForeground: "#2c2825",
      buttonSecondaryBackground: "#dbd7d2",
      buttonSecondaryForeground: "#2c2825",
      link: "#1565c0",
      focusRing: "#8a6d15",
      selectionBackground: "#c9a227",
      selectionForeground: "#2c2825",
      overlay: "rgba(44, 40, 37, 0.25)",
      glow: "rgba(201, 162, 39, 0.18)",
      }),
      code: { preset: 'solar-ash', tokens: resolveCodeThemeTokens('solar-ash', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#16120d",
      surface: "#221c16",
      surfaceElevated: "#2e261e",
      border: "#493d31",
      textPrimary: "#e5e0dc",
      textSecondary: "#b8ada3",
      textMuted: "#958a7e",
      accent: "#e0c05d",
      accentHover: "#e6cd7f",
      accentForeground: "#0d1117",
      success: "#3fb950",
      warning: "#d29922",
      danger: "#f85149",
      info: "#58a6ff",
      focusRing: "#e0c05d",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(224, 192, 93, 0.25)",
      surfaceMuted: "#1d1711",
      borderStrong: "#84705d",
      }),
      code: { preset: 'solar-ash', tokens: resolveCodeThemeTokens('solar-ash', 'dark') },
    },
  },
};
