import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_SWEET_NIGHTMARE: ThemeFamily = {
  schemaVersion: 2,
  id: "sweet-nightmare",
  name: "Sweet Nightmare",
  aliases: ["builtin-sweet-nightmare","sweet-nightmare"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f6f6f7",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#d2cfd3",
      textPrimary: "#231f24",
      textSecondary: "#5c545f",
      textMuted: "#796f7b",
      accent: "#357983",
      accentHover: "#2c646d",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#357983",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(53, 121, 131, 0.18)",
      surfaceMuted: "#efeeef",
      borderStrong: "#969098",
      }),
      code: { preset: 'sweet-nightmare', tokens: resolveCodeThemeTokens('sweet-nightmare', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#8BC7D0",
      background: "#211923",
      surface: "#2D2130",
      surfaceElevated: "#412A3A",
      surfaceMuted: "#37283A",
      border: "#675B6E",
      borderStrong: "#8A6D91",
      textPrimary: "#F3EDEB",
      textSecondary: "#CDBEC9",
      textMuted: "#BBA7B6",
      foreground: "#F3EDEB",
      foregroundMuted: "#CDBEC9",
      foregroundSubtle: "#BBA7B6",
      accentHover: "#A2D3DC",
      accentForeground: "#1A121C",
      success: "#7FCFA9",
      successForeground: "#1A121C",
      warning: "#F0B880",
      warningForeground: "#1A121C",
      danger: "#F0739E",
      dangerForeground: "#1A121C",
      info: "#B995C8",
      inputBackground: "#37283A",
      inputForeground: "#F3EDEB",
      placeholder: "#BBA7B6",
      disabledForeground: "#988494",
      buttonPrimaryBackground: "#8BC7D0",
      buttonPrimaryForeground: "#1A121C",
      buttonSecondaryBackground: "#412A3A",
      buttonSecondaryForeground: "#F3EDEB",
      link: "#8BC7D0",
      focusRing: "#E18AAF",
      selectionBackground: "#633D59",
      selectionForeground: "#F3EDEB",
      overlay: "rgba(33, 25, 35, 0.75)",
      glow: "rgba(139, 199, 208, 0.25)",
      }),
      code: { preset: 'sweet-nightmare', tokens: resolveCodeThemeTokens('sweet-nightmare', 'dark') },
    },
  },
};
