import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_SYNTHWAVE_HARBOR: ThemeFamily = {
  schemaVersion: 2,
  id: "synthwave-harbor",
  name: "Synthwave Harbor",
  aliases: ["builtin-synthwave-harbor"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f5f5f7",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#cbced7",
      textPrimary: "#1a1d29",
      textSecondary: "#495169",
      textMuted: "#646d87",
      accent: "#df0c68",
      accentHover: "#c20a5a",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#df0c68",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(223, 12, 104, 0.18)",
      surfaceMuted: "#ecedf0",
      borderStrong: "#878da1",
      }),
      code: { preset: 'synthwave-harbor', tokens: resolveCodeThemeTokens('synthwave-harbor', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#ff61a6",
      background: "#0a0f1e",
      surface: "#131a2e",
      surfaceElevated: "#1c2440",
      surfaceMuted: "#0e1528",
      border: "#2c3450",
      borderStrong: "#57617b",
      textPrimary: "#e0f7fa",
      textSecondary: "#a8c8d8",
      textMuted: "#6888a0",
      foreground: "#e0f7fa",
      foregroundMuted: "#a8c8d8",
      foregroundSubtle: "#6888a0",
      accentHover: "#ff80b8",
      accentForeground: "#0a0f1e",
      success: "#00e676",
      successForeground: "#0a0f1e",
      warning: "#ffea00",
      warningForeground: "#0a0f1e",
      danger: "#ff5252",
      dangerForeground: "#0a0f1e",
      info: "#00b0ff",
      inputBackground: "#1c2440",
      inputForeground: "#e0f7fa",
      placeholder: "#7391a7",
      disabledForeground: "#6888a0",
      buttonPrimaryBackground: "#ff61a6",
      buttonPrimaryForeground: "#0a0f1e",
      buttonSecondaryBackground: "#1c2440",
      buttonSecondaryForeground: "#e0f7fa",
      link: "#00b0ff",
      focusRing: "#ff61a6",
      selectionBackground: "#ff61a6",
      selectionForeground: "#0a0f1e",
      overlay: "rgba(10, 15, 30, 0.7)",
      glow: "rgba(255, 97, 166, 0.25)",
      }),
      code: { preset: 'synthwave-harbor', tokens: resolveCodeThemeTokens('synthwave-harbor', 'dark') },
    },
  },
};
