import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_TERMINAL_FOREST: ThemeFamily = {
  schemaVersion: 2,
  id: "terminal-forest",
  name: "Terminal Forest",
  aliases: ["builtin-terminal-forest"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f5f7f6",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#cdd5d0",
      textPrimary: "#1c261f",
      textSecondary: "#4f6456",
      textMuted: "#6a8171",
      accent: "#218343",
      accentHover: "#1b6a36",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#218343",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(33, 131, 67, 0.18)",
      surfaceMuted: "#edf0ee",
      borderStrong: "#819187",
      placeholder: "#657a6b",
      }),
      code: { preset: 'terminal-forest', tokens: resolveCodeThemeTokens('terminal-forest', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#09120c",
      surface: "#112217",
      surfaceElevated: "#1a3323",
      border: "#264a33",
      textPrimary: "#d8e8de",
      textSecondary: "#8ba696",
      textMuted: "#5e7a69",
      placeholder: "#809d8b",
      accent: "#47d177",
      accentHover: "#5bed8f",
      accentForeground: "#000000",
      success: "#1b5e20",
      warning: "#9e4a00",
      danger: "#b71c1c",
      info: "#5cad79",
      focusRing: "#47d177",
      overlay: "rgba(0,0,0,0.7)",
      glow: "rgba(71, 209, 119, 0.25)",
      surfaceMuted: "#0d1a11",
      borderStrong: "#3c6b4b",
      dangerForeground: "#ffffff",
      warningForeground: "#ffffff",
      successForeground: "#ffffff",
      }),
      code: { preset: 'terminal-forest', tokens: resolveCodeThemeTokens('terminal-forest', 'dark') },
    },
  },
};
