import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_TOKYO_NIGHT: ThemeFamily = {
  schemaVersion: 2,
  id: "tokyo-night",
  name: "Forge Tokyo",
  aliases: ["builtin-tokyo-night"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f6f6f7",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#cfcfd3",
      textPrimary: "#1e1f24",
      textSecondary: "#53545f",
      textMuted: "#6f707c",
      accent: "#0d50dd",
      accentHover: "#0c45c0",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#0d50dd",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(13, 80, 221, 0.18)",
      surfaceMuted: "#eeeeef",
      borderStrong: "#8b8c95",
      }),
      code: { preset: 'tokyo-night', tokens: resolveCodeThemeTokens('tokyo-night', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#1a1b26",
      surface: "#24283b",
      surfaceElevated: "#363b54",
      border: "#565f89",
      textPrimary: "#a9b1d6",
      textSecondary: "#9aa5ce",
      textMuted: "#8088ab",
      accent: "#7aa2f7",
      accentHover: "#bb9af7",
      accentForeground: "#1a1b26",
      success: "#9ece6a",
      warning: "#e0af68",
      danger: "#f7768e",
      info: "#7dcfff",
      focusRing: "#7aa2f7",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(122, 162, 247, 0.25)",
      surfaceMuted: "#1f2335",
      borderStrong: "#a9b1d6",
      }),
      code: { preset: 'tokyo-night', tokens: resolveCodeThemeTokens('tokyo-night', 'dark') },
    },
  },
};
