import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_TOXIC_LIMEWIRE: ThemeFamily = {
  schemaVersion: 2,
  id: "toxic-limewire",
  name: "Toxic Limewire",
  aliases: ["builtin-toxic-limewire"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f6f6f6",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#cfd3d0",
      textPrimary: "#1f2320",
      textSecondary: "#555e56",
      textMuted: "#707a72",
      accent: "#637e07",
      accentHover: "#4c6105",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#637e07",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(99, 126, 7, 0.18)",
      surfaceMuted: "#eeefee",
      borderStrong: "#888f8a",
      placeholder: "#6e7770",
      }),
      code: { preset: 'toxic-limewire', tokens: resolveCodeThemeTokens('toxic-limewire', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#c6ff00",
      background: "#0f1410",
      surface: "#1c2319",
      surfaceElevated: "#2a3225",
      surfaceMuted: "#151c12",
      border: "#3a4532",
      borderStrong: "#5a6552",
      textPrimary: "#e8f5e9",
      textSecondary: "#b8d0b0",
      textMuted: "#789070",
      foreground: "#e8f5e9",
      foregroundMuted: "#b8d0b0",
      foregroundSubtle: "#789070",
      accentHover: "#d8ff40",
      accentForeground: "#0f1410",
      success: "#76ff03",
      successForeground: "#0f1410",
      warning: "#ffea00",
      warningForeground: "#0f1410",
      danger: "#ff1744",
      dangerForeground: "#0f1410",
      info: "#00e5ff",
      inputBackground: "#2a3225",
      inputForeground: "#e8f5e9",
      placeholder: "#899e82",
      disabledForeground: "#789070",
      buttonPrimaryBackground: "#c6ff00",
      buttonPrimaryForeground: "#0f1410",
      buttonSecondaryBackground: "#2a3225",
      buttonSecondaryForeground: "#e8f5e9",
      link: "#00e5ff",
      focusRing: "#c6ff00",
      selectionBackground: "#c6ff00",
      selectionForeground: "#0f1410",
      overlay: "rgba(15, 20, 16, 0.7)",
      glow: "rgba(198, 255, 0, 0.25)",
      }),
      code: { preset: 'toxic-limewire', tokens: resolveCodeThemeTokens('toxic-limewire', 'dark') },
    },
  },
};
