import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_ULTRAVIOLET_RAIN: ThemeFamily = {
  schemaVersion: 2,
  id: "ultraviolet-rain",
  name: "Ultraviolet Rain",
  aliases: ["builtin-ultraviolet-rain"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f6f6f7",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      border: "#d0cfd4",
      textPrimary: "#201e24",
      textSecondary: "#565360",
      textMuted: "#726e7c",
      accent: "#470cdf",
      accentHover: "#3e0ac2",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#9a6700",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#470cdf",
      overlay: "rgba(0, 0, 0, 0.4)",
      glow: "rgba(71, 12, 223, 0.18)",
      surfaceMuted: "#eeeeef",
      borderStrong: "#8e8c96",
      }),
      code: { preset: 'ultraviolet-rain', tokens: resolveCodeThemeTokens('ultraviolet-rain', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#8f63ff",
      background: "#121018",
      surface: "#1e1a2e",
      surfaceElevated: "#2c2840",
      surfaceMuted: "#181430",
      border: "#3e3858",
      borderStrong: "#635d84",
      textPrimary: "#ede7f6",
      textSecondary: "#c4b8e0",
      textMuted: "#8a80a8",
      foreground: "#ede7f6",
      foregroundMuted: "#c4b8e0",
      foregroundSubtle: "#8a80a8",
      accentHover: "#9e7dff",
      accentForeground: "#121018",
      success: "#b9f6ca",
      successForeground: "#121018",
      warning: "#ffe57f",
      warningForeground: "#121018",
      danger: "#ff8a80",
      dangerForeground: "#121018",
      info: "#80d8ff",
      inputBackground: "#2c2840",
      inputForeground: "#ede7f6",
      placeholder: "#8a80a8",
      disabledForeground: "#8a80a8",
      buttonPrimaryBackground: "#8f63ff",
      buttonPrimaryForeground: "#121018",
      buttonSecondaryBackground: "#2c2840",
      buttonSecondaryForeground: "#ede7f6",
      link: "#80d8ff",
      focusRing: "#8f63ff",
      selectionBackground: "#8f63ff",
      selectionForeground: "#121018",
      overlay: "rgba(18, 16, 24, 0.7)",
      glow: "rgba(143, 99, 255, 0.25)",
      }),
      code: { preset: 'ultraviolet-rain', tokens: resolveCodeThemeTokens('ultraviolet-rain', 'dark') },
    },
  },
};
