import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_VENICE: ThemeFamily = {
  schemaVersion: 2,
  id: "venice",
  name: "Venice Parity Dark",
  aliases: ["builtin-venice"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f4f4f5",
      surface: "#fafafa",
      surfaceElevated: "#ffffff",
      border: "#d4d4d8",
      textPrimary: "#1c1c1f",
      textSecondary: "#5b5b63",
      textMuted: "#8a8a92",
      accent: "#c81e3f",
      accentHover: "#a51836",
      accentForeground: "#ffffff",
      success: "#3f9142",
      warning: "#a16207",
      danger: "#dc2626",
      info: "#1d4ed8",
      focusRing: "#c81e3f",
      overlay: "rgba(28, 28, 31, 0.35)",
      glow: "rgba(200, 30, 63, 0.10)",
      surfaceMuted: "#ececee",
      borderStrong: "#71717a",
      }),
      code: { preset: 'venice', tokens: resolveCodeThemeTokens('venice', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#050505",
      surface: "#0d0d10",
      surfaceElevated: "#16161a",
      border: "#26262c",
      textPrimary: "#dedcdf",
      textSecondary: "#8c8892",
      textMuted: "#7f7a86",
      accent: "#ef555f",
      accentHover: "#f65964",
      accentForeground: "#050505",
      success: "#6fbf73",
      warning: "#d6a84f",
      danger: "#ef4444",
      info: "#7da7ff",
      focusRing: "#ef555f",
      overlay: "rgba(5, 5, 5, 0.7)",
      glow: "rgba(239, 85, 95, 0.12)",
      surfaceMuted: "#08080a",
      borderStrong: "#55555e",
      }),
      code: { preset: 'venice', tokens: resolveCodeThemeTokens('venice', 'dark') },
    },
  },
};
