---
# This is an example color .yaml templet
# each use hex values to assign each color a value
# do not leave any value blank
# "details" is the name of the theme
accent: "#63b3ed"
background: "#050a0f"
details: "Venice Parity Dark"
foreground: "#f4f6f8"
terminal_colors:
  bright:
    black: "#687483"
    blue: "#2b6cb0"
    cyan: "#7da7ff"
    green: "#74d66a"
    magenta: "#63b3ed"
    red: "#ef4444"
    white: "#f4f6f8"
    yellow: "#d6a84f"
  normal:
    black: "#050a0f"
    blue: "#63b3ed"
    cyan: "#7da7ff"
    green: "#74d66a"
    magenta: "#63b3ed"
    red: "#ef4444"
    white: "#a6b0bc"
    yellow: "#d6a84f"
