// Code Owner: fayeblade (@spearchucker667)
// Image generation preview + recent history — extracted from ImageModule.
import React from "react";
import { CollapsibleSection } from "./CollapsibleSection";
import { GalleryImage } from "../types/storage";
import { AppState, AppDispatch, ImageDraft } from "../types/app";

interface ImageGenerationPreviewProps {
  state: AppState;
  dispatch: AppDispatch;
  draft: ImageDraft;
  recentHistory: GalleryImage[];
  onExpand: (img: GalleryImage) => void;
  onLoadSettings: (img: GalleryImage) => void;
}

export function ImageGenerationPreview({
  state,
  dispatch,
  draft,
  recentHistory,
  onExpand,
  onLoadSettings,
}: ImageGenerationPreviewProps) {
  function patch(updates: Partial<ImageDraft>) {
    dispatch({ type: "SET_IMAGE_DRAFT", patch: updates });
  }

  return (
    <>
      <div className="grid">
        <div className="image-preview">
          {draft.generationProgress ? (
            <div style={{ display: "grid", placeItems: "center", gap: "8px" }}>
              <div className="muted">{draft.generationProgress}</div>
              <div className="progress-bar"><div className="progress-bar-fill" /></div>
            </div>
          ) : draft.currentImages && draft.currentImages.length > 1 ? (
            <div className={`batch-preview-grid items-${draft.currentImages.length}`}>
              {draft.currentImages.map((savedDoc: any, idx: number) => (
                <img
                  key={savedDoc.id || idx}
                  src={savedDoc.image}
                  alt={`Generated by Venice ${idx + 1}`}
                  tabIndex={0}
                  role="button"
                  aria-label={`View image details: ${savedDoc.prompt || "Generated image"}`}
                  onClick={() => onExpand(savedDoc)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter" || e.key === " ") {
                      e.preventDefault();
                      onExpand(savedDoc);
                    }
                  }}
                  className="batch-img-thumb"
                />
              ))}
            </div>
          ) : draft.currentImage ? (
            <img
              src={draft.currentImage}
              alt="Generated by Venice"
              tabIndex={0}
              role="button"
              aria-label="View generated image details"
              onClick={() =>
                onExpand(
                  state.gallery.find(
                    (x: any) => x.id === draft.lastSavedImageId
                  ) || {
                    id: draft.lastSavedImageId || "preview",
                    image: draft.currentImage,
                    prompt: draft.prompt,
                    model: state.selectedImageModel,
                    timestamp: Date.now(),
                  }
                )
              }
              onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === " ") {
                  e.preventDefault();
                  onExpand(
                    state.gallery.find(
                      (x: any) => x.id === draft.lastSavedImageId
                    ) || {
                      id: draft.lastSavedImageId || "preview",
                      image: draft.currentImage,
                      prompt: draft.prompt,
                      model: state.selectedImageModel,
                      timestamp: Date.now(),
                    }
                  );
                }
              }}
            />
          ) : (
            <div className="muted">Generated image preview</div>
          )}
        </div>
        <div className="small muted">
          Prompt and controls persist when switching menus. Generated images
          auto-save to Gallery.
        </div>
      </div>

      {recentHistory.length > 0 && (
        <div style={{ padding: "0 20px 20px" }}>
          <CollapsibleSection title="Recent Prompts & Settings" defaultOpen={false}>
            <div className="grid two" style={{ gap: 16 }}>
              {recentHistory.map((img) => (
                <div
                  key={img.id}
                  className="history-card"
                  style={{
                    display: "flex",
                    gap: 12,
                    padding: 16,
                    backgroundColor: "var(--panel-strong)",
                    borderRadius: 24,
                    alignItems: "center",
                  }}
                >
                  <img
                    src={img.image}
                    alt=""
                    style={{ width: 64, height: 64, objectFit: "cover", borderRadius: 12 }}
                  />
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div
                      className="small"
                      style={{
                        whiteSpace: "nowrap",
                        overflow: "hidden",
                        textOverflow: "ellipsis",
                        fontWeight: 500,
                      }}
                    >
                      {img.prompt}
                    </div>
                    <div className="tiny muted mt-1">
                      {img.model} • {img.aspectRatio || `${img.width}x${img.height}`}
                    </div>
                    <div className="chip-row mt-2" style={{ gap: 6 }}>
                      <button className="btn small" onClick={() => onLoadSettings(img)}>
                        Load Settings
                      </button>
                      <button
                        className="btn small"
                        onClick={() => {
                          patch({ prompt: img.prompt });
                          dispatch({
                            type: "ADD_TOAST",
                            toast: { id: crypto.randomUUID(), message: "Copied prompt", type: "info" },
                          });
                        }}
                      >
                        Copy Prompt
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </CollapsibleSection>
        </div>
      )}
    </>
  );
}
