/**
 * @fileoverview Sentinel-aware i18n verifier. Validates:
 *   1. Resource completeness across all 12 locales and 12 namespaces.
 *   2. Source-code translation key existence in canonical en-US catalogs.
 *   3. Rejects `[XX]` sentinel prefixes produced by the obsolete
 *      `scripts/generate-locales.cjs` tool.
 *   4. Rejects `__MISSING__:` placeholder values produced by the new
 *      `scripts/sync-catalogs.cjs` and key-name fallback placeholders (e.g.
 *      `"contextMenu.saveAs": "contextMenu.saveAs"`) are present only when
 *      paired with a clean translator follow-up.
 *   5. Interpolation variable parity.
 *   6. Localized documentation completeness.
 *   7. Writes a *truthful* `docs/i18n/translation-status.json` — never claims
 *      `complete` unless the locale passes every check with zero diverging
 *      sentinels/missing placeholders/unapproved identical values.
 */

"use strict";

const fs = require("fs");
const path = require("path");
const {
  extractKeysFromSource,
  VISIBLE_NAMESPACES,
} = require("./extract-i18n-keys.cjs");

const ROOT_DIR = path.join(__dirname, "..");
const RESOURCES_DIR = path.join(ROOT_DIR, "src", "i18n", "resources");
const DOCS_I18N_DIR = path.join(ROOT_DIR, "docs", "i18n");
const STATUS_METADATA_PATH = path.join(
  DOCS_I18N_DIR,
  "translation-status.json",
);
const NATIVE_REVIEW_STATUS_PATH = path.join(
  DOCS_I18N_DIR,
  "native-review-status.json",
);
const IDENTICAL_VALUE_ALLOWLIST_PATH = path.join(
  DOCS_I18N_DIR,
  "identical-value-allowlist.json",
);

const EXPECTED_LOCALES = [
  "en-US",
  "es",
  "fr",
  "de",
  "pt-BR",
  "ru",
  "zh-CN",
  "ja",
  "hi",
  "ar",
  "ko",
  "sv-SE",
];

const NAMESPACES = VISIBLE_NAMESPACES;

const REQUIRED_DOCS = [
  "README.md",
  "ABOUT.md",
  "FAQ.md",
  "SUPPORT.md",
  "PRIVACY.md",
  "SECURITY.md",
  "CONTRIBUTING.md",
];

// Identical-to-en-US values that the verifier must accept as legitimately
// untranslated. These fall into three families:
//   1. Product / brand / model names (Venice Forge, GLM 5.2, …).
//   2. Technical single-word tokens that are file-format / shortcut names
//      (PNG, JSON, ESC, Auto, …) — translating them changes the meaning or
//      breaks keyboard / API contracts.
//   3. Interpolation-only format strings (e.g. "{{count}} / {{max}} tokens")
//      where the placeholders carry the meaning and prose is absent in
//      practice.
//
// Add to this set with care: prefer translating prose over silently
// preserving English.
const ALLOWLISTED_IDENTICAL = new Set([
  // Brand / product / vendor names
  "Venice Forge",
  "Venice",
  "Venice.ai",
  "Jina",
  "Jina.ai",
  "GLM 5.2",
  "zai-org-glm-5-2",
  "together, groq, anthropic",
  // Format / protocol / algorithm tokens
  "API",
  "JSON",
  "PNG",
  "JPEG",
  "WebP",
  "MP4",
  "TTS",
  "ST",
  "OS",
  "IDB",
  "SHA-256",
  "Argon2id",
  "XChaCha20-Poly1305",
  "base64",
  "LTR",
  "RTL",
  // Keyboard / UI shortcut tokens
  "ESC",
  // Single-word mode / pack / config labels (intentional English loanwords)
  "Auto",
  "Retro",
  "Minimal",
  "Tactile",
  // Surface labels that are also widely-accepted English product names
  "Conversation",
  "Persona",
  "Scenario",
  "Lorebook",
  "Playground",
  "Provider",
  "RP Studio",
  "Traffic Inspector",
  "System",
  "Optional",
  "Mode",
  "Mode ", // trailing space tolerated
  "Audio",
  "Video",
  "Markdown",
  "Status:",
  "Sources",
  "Top-p",
  "Seed",
  "Family Safe Mode",
  // Verbs that double as UI label (no localized counterpart simplified)
  "Chat",
  "Documents",
  "Error",
  "Date",
  "Prompts",
  "Embeddings",
  "Status",
  "Updates",
  "Workflows",
  "complete",
  "failed",
  "true",
  // Example / placeholder identifiers used in onboarding copy
  "card-1",
  "conv-1",
  "lib-1",
  "q1",
  "q2",
  "rpchat-1",
  // Interpolation-bearing format strings — placeholders carry the meaning
  "{{count}} / {{max}} tokens",
  "{{message}}",
  "Format: v{{version}}{{appVersion}}",
  "Volume",
  "Volume: {{volume}}%",
]);

// Generated by the obsolete generate-locales.cjs (lines 837–849). Captured
// here as a constant so the verifier remains self-documenting.
const SENTINEL_PATTERN = /^\s*(?:\[[A-Za-z][A-Za-z-]{1,10}\]|Tr:)\s/;
const MISSING_MARKER_PATTERN = /^\s*__MISSING__:/;

/**
 * Detects key-name fallback placeholders such as
 * `"contextMenu.saveAs": "contextMenu.saveAs"` or
 * `"imageStudioRuntime.enhancementSafetyBlockedMandatory":
 *  "imageStudioRuntime.enhancementSafetyBlockedMandatory"`.
 * These are produced when a sync tool cannot find a translation and copies the
 * dotted key into the value slot. They evade the legacy sentinel/missing-marker
 * checks but are still untranslated and must not be counted as localized.
 *
 * Both the full `namespace.relative.key` path and the path relative to the
 * namespace root are accepted, because different sync tools write different
 * prefixes. Require at least one dot in the matched path to avoid flagging
 * legitimate single-word translations that happen to equal the leaf key.
 */
function isKeyNameFallback(value, fullKeyPath, relativeKeyPath) {
  if (typeof value !== "string") return false;
  const trimmed = value.trim();
  const candidates = [fullKeyPath, relativeKeyPath].filter(
    (path) => typeof path === "string" && path.includes("."),
  );
  for (const keyPath of candidates) {
    if (trimmed === keyPath) return true;
    if (
      trimmed.startsWith(keyPath) &&
      /^\s+\{\{/.test(trimmed.slice(keyPath.length))
    ) {
      return true;
    }
  }
  return false;
}

function extractKeys(obj, prefix = "") {
  const keys = {};
  for (const [k, v] of Object.entries(obj)) {
    const keyPath = prefix ? `${prefix}.${k}` : k;
    if (typeof v === "object" && v !== null && !Array.isArray(v)) {
      Object.assign(keys, extractKeys(v, keyPath));
    } else {
      keys[keyPath] = v;
    }
  }
  return keys;
}

function flattenTree(obj, prefix = "", out = []) {
  for (const [k, v] of Object.entries(obj)) {
    const keyPath = prefix ? `${prefix}.${k}` : k;
    if (v && typeof v === "object" && !Array.isArray(v))
      flattenTree(v, keyPath, out);
    else out.push([keyPath, v]);
  }
  return out;
}

function extractInterpolationVars(str) {
  if (typeof str !== "string") return [];
  const matches = str.match(/\{\{([^}]+)\}\}/g) || [];
  // i18next treats {{name}} as a shared variable — every reference in a string
  // resolves to the same value at runtime. Dedup after sort so a translation
  // that legitimately re-references an existing variable does not trigger an
  // interpolation-mismatch false positive.
  const seen = new Set();
  for (const m of matches) {
    seen.add(m.replace(/[{}]/g, "").trim());
  }
  return [...seen].sort();
}

function applyCliFlags(args) {
  const strict = args.includes("--strict");
  const allowSentinels = args.includes("--allow-sentinels");
  const allowMissingMarkers = args.includes("--allow-missing-markers");
  const allowKeyNameFallbacks = args.includes("--allow-key-name-fallbacks");
  const writeStatus = args.includes("--write-status");
  return {
    strict,
    allowSentinels,
    allowMissingMarkers,
    allowKeyNameFallbacks,
    writeStatus,
  };
}

function loadNativeReviewStatus(filePath = NATIVE_REVIEW_STATUS_PATH) {
  if (!fs.existsSync(filePath)) return { schemaVersion: 1, locales: {} };
  const parsed = JSON.parse(fs.readFileSync(filePath, "utf8"));
  return parsed && typeof parsed === "object" && parsed.locales
    ? parsed
    : { schemaVersion: 1, locales: {} };
}

function loadLocaleIdenticalAllowlist(
  filePath = IDENTICAL_VALUE_ALLOWLIST_PATH,
) {
  if (!fs.existsSync(filePath)) return {};
  const parsed = JSON.parse(fs.readFileSync(filePath, "utf8"));
  return parsed && typeof parsed === "object" && parsed.locales
    ? parsed.locales
    : {};
}

function runVerification({
  strict = false,
  allowSentinels = false,
  allowMissingMarkers = false,
  allowKeyNameFallbacks = false,
  skipSourceInventory = false,
  writeStatus = false,
  statusPath: statusPathOverride,
  locales: localeOverride,
  namespaces: namespaceOverride,
  resourcesDir: resourcesDirOverride,
  docsDir: docsDirOverride,
  docsRequired: docsRequiredOverride,
  nativeReviewStatusPath,
  nativeReviewStatus,
  identicalValueAllowlistPath,
  identicalValueAllowlist,
} = {}) {
  const errors = [];
  const warnings = [];

  const activeLocales = localeOverride || EXPECTED_LOCALES;
  const activeNamespaces = namespaceOverride || NAMESPACES;
  const activeResourcesDir = resourcesDirOverride || RESOURCES_DIR;
  const activeDocsDir = docsDirOverride || DOCS_I18N_DIR;
  const activeDocs = docsRequiredOverride || REQUIRED_DOCS;
  const reviewEvidence =
    nativeReviewStatus ||
    loadNativeReviewStatus(nativeReviewStatusPath || NATIVE_REVIEW_STATUS_PATH);
  const localeIdenticalValues =
    identicalValueAllowlist ||
    loadLocaleIdenticalAllowlist(
      identicalValueAllowlistPath || IDENTICAL_VALUE_ALLOWLIST_PATH,
    );

  // 1. Verify resource directories exist
  for (const locale of activeLocales) {
    const dir = path.join(activeResourcesDir, locale);
    if (!fs.existsSync(dir)) {
      errors.push(
        `Missing resource directory for locale '${locale}' at ${dir}`,
      );
    }
  }

  // 2. Load en-US canonical resources
  const enUSResources = {};
  const enUSLeafKeys = {};
  for (const ns of activeNamespaces) {
    const file = path.join(activeResourcesDir, "en-US", `${ns}.json`);
    if (!fs.existsSync(file)) {
      errors.push(`Missing canonical en-US namespace file: ${file}`);
      continue;
    }
    try {
      const parsed = JSON.parse(fs.readFileSync(file, "utf8"));
      enUSResources[ns] = parsed;
      enUSLeafKeys[ns] = extractKeys(parsed);
      for (const [, v] of flattenTree(parsed)) {
        if (typeof v !== "string") continue;
        if (SENTINEL_PATTERN.test(v)) {
          errors.push(
            `en-US canonical seed for '${ns}' contains sentinel value: "${v}"`,
          );
        }
        if (MISSING_MARKER_PATTERN.test(v)) {
          errors.push(
            `en-US canonical seed for '${ns}' contains __MISSING__ marker: "${v}"`,
          );
        }
      }
    } catch (err) {
      errors.push(
        `Failed to parse en-US namespace file ${file}: ${err.message}`,
      );
    }
  }

  // 3. Verify source code keys exist in canonical en-US resources
  // Tests pass `skipSourceInventory: true` so they can drive the verifier
  // against synthetic en-US fixtures (otherwise the AST extractor would
  // walk the real src/ tree and generate ~410 keys the fixture lacks).
  let sourceKeys = [];
  if (!skipSourceInventory) {
    sourceKeys = extractKeysFromSource();
    for (const item of sourceKeys) {
      const nsKeys = enUSLeafKeys[item.ns];
      if (!nsKeys || !(item.key in nsKeys)) {
        errors.push(
          `Source code key '${item.fullKey}' (at ${item.file}:${item.line}) is missing from canonical en-US catalog.`,
        );
      }
    }
  }

  // 4. Per-locale parity, interpolation, and translation quality checks
  const enUSKeyTotal = Object.values(enUSLeafKeys).reduce(
    (acc, keys) => acc + Object.keys(keys).length,
    0,
  );
  const enUSHasKey = activeLocales.includes("en-US");
  const coverageResults = {
    "en-US": {
      total: enUSHasKey ? enUSKeyTotal : 0,
      translated: enUSHasKey ? enUSKeyTotal : 0,
      identicalUnapproved: 0,
      sentinelValues: 0,
      missingMarkers: 0,
      keyNameFallbacks: 0,
      pendingTranslation: 0,
      pct: 100,
    },
  };

  for (const locale of activeLocales) {
    if (locale === "en-US") continue;
    let localeTotal = 0;
    let localeTranslated = 0;
    let localeIdenticalUnapproved = 0;
    let localeSentinel = 0;
    let localeMissingMarker = 0;
    let localeKeyNameFallback = 0;
    let localePending = 0;
    const localeAllowedIdentical = new Set(localeIdenticalValues[locale] || []);

    for (const ns of activeNamespaces) {
      const file = path.join(activeResourcesDir, locale, `${ns}.json`);
      if (!fs.existsSync(file)) {
        errors.push(`Missing namespace file for ${locale}: ${ns}.json`);
        continue;
      }
      let parsed;
      try {
        parsed = JSON.parse(fs.readFileSync(file, "utf8"));
      } catch (err) {
        errors.push(`Invalid JSON in ${locale}/${ns}.json: ${err.message}`);
        continue;
      }
      const enKeys = enUSLeafKeys[ns] || {};
      const locKeys = extractKeys(parsed);

      // Missing keys
      for (const k of Object.keys(enKeys)) {
        if (!(k in locKeys)) {
          errors.push(`Locale '${locale}' missing key '${ns}:${k}'`);
        } else {
          localeTotal++;
          const enVal = enKeys[k];
          const locVal = locKeys[k];

          if (typeof locVal !== "string") {
            errors.push(
              `Locale '${locale}' key '${ns}:${k}' is not a string (got ${typeof locVal})`,
            );
            continue;
          }

          // Sentinel check (rejects the false-green artefact)
          if (SENTINEL_PATTERN.test(locVal)) {
            localeSentinel++;
            const msg = `Locale '${locale}' key '${ns}:${k}' contains a sentinel prefix: "${locVal.slice(0, 64)}"`;
            if (strict || !allowSentinels) {
              errors.push(msg);
            } else {
              warnings.push(msg);
            }
          }

          // Missing-marker check
          if (MISSING_MARKER_PATTERN.test(locVal)) {
            localeMissingMarker++;
            const msg = `Locale '${locale}' key '${ns}:${k}' still carries __MISSING__ placeholder: "${locVal.slice(0, 64)}"`;
            if (strict || !allowMissingMarkers) {
              errors.push(msg);
            } else {
              warnings.push(msg);
            }
            localePending++;
          }

          // Key-name fallback placeholder check
          const fullKeyPath = `${ns}.${k}`;
          if (isKeyNameFallback(locVal, fullKeyPath, k)) {
            localeKeyNameFallback++;
            const msg = `Locale '${locale}' key '${ns}:${k}' still carries key-name fallback placeholder: "${locVal.slice(0, 64)}"`;
            if (strict || !allowKeyNameFallbacks) {
              errors.push(msg);
            } else {
              warnings.push(msg);
            }
            localePending++;
          }

          // Interpolation variables
          const enVars = extractInterpolationVars(enVal);
          const locVars = extractInterpolationVars(locVal);
          if (enVars.join("|") !== locVars.join("|")) {
            errors.push(
              `Locale '${locale}' key '${ns}:${k}' interpolation mismatch. Expected [${enVars.join(", ")}], got [${locVars.join(", ")}]`,
            );
          }

          // Translation quality
          if (
            SENTINEL_PATTERN.test(locVal) ||
            MISSING_MARKER_PATTERN.test(locVal) ||
            isKeyNameFallback(locVal, fullKeyPath, k)
          ) {
            // Untranslated — does not count as "translated"
          } else if (
            locVal !== enVal ||
            ALLOWLISTED_IDENTICAL.has(enVal) ||
            localeAllowedIdentical.has(enVal)
          ) {
            localeTranslated++;
          } else {
            localeIdenticalUnapproved++;
            errors.push(
              `Locale '${locale}' key '${ns}:${k}' contains unapproved untranslated English text: "${enVal}"`,
            );
          }
        }
      }

      // Orphan keys
      for (const k of Object.keys(locKeys)) {
        if (!(k in enKeys)) {
          errors.push(
            `Locale '${locale}' has orphan key '${ns}:${k}' not found in en-US`,
          );
        }
      }
    }

    const pct =
      localeTotal > 0
        ? parseFloat(((localeTranslated / localeTotal) * 100).toFixed(1))
        : 0;
    coverageResults[locale] = {
      total: localeTotal,
      translated: localeTranslated,
      identicalUnapproved: localeIdenticalUnapproved,
      sentinelValues: localeSentinel,
      missingMarkers: localeMissingMarker,
      keyNameFallbacks: localeKeyNameFallback,
      pendingTranslation: localePending,
      pct,
    };
  }

  // 5. Verify localized documentation directories
  const localeDocsInfo = new Map();
  // Skip the entire docs branch when no docs are required (test fixtures).
  if (activeDocs.length > 0) {
    for (const locale of activeLocales) {
      if (locale === "en-US") continue;
      const locDocsDir = path.join(activeDocsDir, locale);
      if (!fs.existsSync(locDocsDir)) {
        errors.push(
          `Missing documentation directory for locale '${locale}' at ${locDocsDir}`,
        );
        localeDocsInfo.set(locale, { present: 0, total: activeDocs.length });
        continue;
      }
      let present = 0;
      for (const doc of activeDocs) {
        const docPath = path.join(locDocsDir, doc);
        if (fs.existsSync(docPath)) {
          present++;
        } else {
          errors.push(
            `Missing localized doc '${doc}' for locale '${locale}' at ${docPath}`,
          );
        }
      }
      localeDocsInfo.set(locale, { present, total: activeDocs.length });
    }
  }

  // 6. Build truthful status JSON. Catalog integrity and native-language
  // review are independent signals; machine output never self-certifies.
  const hardcodedReportPath = path.join(
    ROOT_DIR,
    "artifacts",
    "i18n",
    "hardcoded-strings.json",
  );
  let runtimeSurfaceFindings = null;
  let runtimeSurfaceFilesScanned = null;
  let runtimeSurfaceExtractor = null;
  if (fs.existsSync(hardcodedReportPath)) {
    try {
      const runtimeReport = JSON.parse(
        fs.readFileSync(hardcodedReportPath, "utf8"),
      );
      runtimeSurfaceFindings = Number.isInteger(runtimeReport.findingsCount)
        ? runtimeReport.findingsCount
        : null;
      runtimeSurfaceFilesScanned = Number.isInteger(runtimeReport.fileCount)
        ? runtimeReport.fileCount
        : null;
      runtimeSurfaceExtractor =
        typeof runtimeReport.extractor === "string"
          ? runtimeReport.extractor
          : null;
    } catch {
      runtimeSurfaceFindings = null;
    }
  }
  const runtimeSurfaceCoverage = runtimeSurfaceFindings === 0 ? 100 : 0;

  const statusMetadata = {
    schemaVersion: 4,
    updatedAt: new Date().toISOString(),
    extractorArtifact: "scripts/extract-i18n-keys.cjs (TS Compiler API)",
    verifier:
      "scripts/verify-i18n.cjs (sentinel + missing-marker + key-name-fallback aware)",
    runtimeSurfaceArtifact: "artifacts/i18n/hardcoded-strings.json",
    runtimeSurfaceFindings,
    runtimeSurfaceFilesScanned,
    runtimeSurfaceExtractor,
    locales: {},
  };

  const localeNames = {
    "en-US": "English (US)",
    es: "Español",
    fr: "Français",
    de: "Deutsch",
    "pt-BR": "Português (Brasil)",
    ru: "Русский",
    "zh-CN": "简体中文",
    ja: "日本語",
    hi: "हिन्दी",
    ar: "العربية",
    ko: "한국어",
    "sv-SE": "Svenska",
  };

  for (const locale of activeLocales) {
    const cov = coverageResults[locale];
    const docs = localeDocsInfo.get(locale) || { present: 0, total: 0 };
    const docsPct =
      docs.total > 0
        ? parseFloat(((docs.present / docs.total) * 100).toFixed(1))
        : 100;
    const catalogStatus =
      cov.pct >= 100 &&
      cov.sentinelValues === 0 &&
      cov.missingMarkers === 0 &&
      cov.keyNameFallbacks === 0 &&
      cov.identicalUnapproved === 0 &&
      docsPct >= 100
        ? "complete"
        : cov.sentinelValues > 0 ||
            cov.missingMarkers > 0 ||
            cov.keyNameFallbacks > 0
          ? "pending-translation"
          : "in-progress";
    const evidence =
      locale === "en-US"
        ? { status: "source-language", reviewer: null, reviewedAt: null }
        : reviewEvidence.locales?.[locale] || {
            status: "first-pass-machine",
            reviewer: null,
            reviewedAt: null,
          };
    const reviewStatus = evidence.status || "first-pass-machine";
    statusMetadata.locales[locale] = {
      name: localeNames[locale] || locale,
      catalogStructuralCoverage: cov.pct,
      runtimeSurfaceCoverage,
      linguisticReviewStatus: reviewStatus,
      uiCoveragePercent: cov.pct,
      canonicalKeyTotal: cov.total,
      translatedKeyTotal: cov.translated,
      sentinelLeaves: cov.sentinelValues,
      missingMarkerLeaves: cov.missingMarkers,
      keyNameFallbackLeaves: cov.keyNameFallbacks,
      identicalUnapprovedLeaves: cov.identicalUnapproved,
      docsCoveragePercent: docsPct,
      docsPresent: docs.present,
      docsTotal: docs.total,
      docs: docsPct >= 100 ? "translated" : "pending-human-translation",
      catalogStatus,
      reviewStatus,
      reviewer: evidence.reviewer || null,
      reviewedAt: evidence.reviewedAt || null,
      lastUpdated: new Date().toISOString(),
    };
  }

  if (writeStatus) {
    const targetPath = statusPathOverride || STATUS_METADATA_PATH;
    fs.mkdirSync(path.dirname(targetPath), { recursive: true });
    fs.writeFileSync(
      targetPath,
      JSON.stringify(statusMetadata, null, 2) + "\n",
      "utf8",
    );
  }

  // Summary
  if (warnings.length > 0) {
    console.warn(
      `\n⚠ ${warnings.length} warnings (--no-strict or per-flag override active):`,
    );
    warnings.forEach((w) => console.warn(` - ${w}`));
  }

  if (errors.length > 0) {
    console.error(`\n❌ i18n Verification Failed (${errors.length} errors):`);
    errors.forEach((e) => console.error(` - ${e}`));
    return {
      ok: false,
      errors,
      warnings,
      coverageResults,
      status: statusMetadata,
    };
  }

  console.log(
    `\n✓ i18n Verification Passed (${activeLocales.length} locales, ${activeNamespaces.length} namespaces); sentinel, missing-marker, and key-name-fallback aware.`,
  );
  return {
    ok: true,
    errors: [],
    warnings,
    coverageResults,
    status: statusMetadata,
  };
}

if (require.main === module) {
  const {
    strict,
    allowSentinels,
    allowMissingMarkers,
    allowKeyNameFallbacks,
    writeStatus,
  } = applyCliFlags(process.argv.slice(2));
  const result = runVerification({
    strict,
    allowSentinels,
    allowMissingMarkers,
    allowKeyNameFallbacks,
    writeStatus,
  });
  process.exit(result.ok ? 0 : 1);
}

module.exports = {
  runVerification,
  SENTINEL_PATTERN,
  MISSING_MARKER_PATTERN,
  isKeyNameFallback,
  EXPECTED_LOCALES,
  EXPECTED_NAMESPACES: NAMESPACES,
  NATIVE_REVIEW_STATUS_PATH,
  IDENTICAL_VALUE_ALLOWLIST_PATH,
  applyCliFlags,
  loadNativeReviewStatus,
  loadLocaleIdenticalAllowlist,
};
